/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CondenserConfigInitParameters struct {

	// (Updatable) LLM selection configuration.
	LlmSelection []CondenserConfigLlmSelectionInitParameters `json:"llmSelection,omitempty" tf:"llm_selection,omitempty"`
}

type CondenserConfigLlmSelectionInitParameters struct {

	// (Updatable) The type of LLM selection.
	LlmSelectionType *string `json:"llmSelectionType,omitempty" tf:"llm_selection_type,omitempty"`

	// (Updatable) The id of the GenAI model
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/generativeai/v1alpha1.Model
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`

	// Reference to a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDRef *v1.Reference `json:"modelIdRef,omitempty" tf:"-"`

	// Selector for a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDSelector *v1.Selector `json:"modelIdSelector,omitempty" tf:"-"`
}

type CondenserConfigLlmSelectionObservation struct {

	// (Updatable) The type of LLM selection.
	LlmSelectionType *string `json:"llmSelectionType,omitempty" tf:"llm_selection_type,omitempty"`

	// (Updatable) The id of the GenAI model
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`
}

type CondenserConfigLlmSelectionParameters struct {

	// (Updatable) The type of LLM selection.
	// +kubebuilder:validation:Optional
	LlmSelectionType *string `json:"llmSelectionType" tf:"llm_selection_type,omitempty"`

	// (Updatable) The id of the GenAI model
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/generativeai/v1alpha1.Model
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`

	// Reference to a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDRef *v1.Reference `json:"modelIdRef,omitempty" tf:"-"`

	// Selector for a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDSelector *v1.Selector `json:"modelIdSelector,omitempty" tf:"-"`
}

type CondenserConfigObservation struct {

	// (Updatable) LLM selection configuration.
	LlmSelection []CondenserConfigLlmSelectionObservation `json:"llmSelection,omitempty" tf:"llm_selection,omitempty"`
}

type CondenserConfigParameters struct {

	// (Updatable) LLM selection configuration.
	// +kubebuilder:validation:Optional
	LlmSelection []CondenserConfigLlmSelectionParameters `json:"llmSelection" tf:"llm_selection,omitempty"`
}

type ConversationConfigInitParameters struct {

	// (Updatable) Retention period (in hours) for conversations. The TTL starts from the time the conversation was last updated.
	ConversationsRetentionInHours *int64 `json:"conversationsRetentionInHours,omitempty" tf:"conversations_retention_in_hours,omitempty"`

	// (Updatable) Retention period (in hours) for responses. The TTL starts from the time the response was created.
	ResponsesRetentionInHours *int64 `json:"responsesRetentionInHours,omitempty" tf:"responses_retention_in_hours,omitempty"`
}

type ConversationConfigObservation struct {

	// (Updatable) Retention period (in hours) for conversations. The TTL starts from the time the conversation was last updated.
	ConversationsRetentionInHours *int64 `json:"conversationsRetentionInHours,omitempty" tf:"conversations_retention_in_hours,omitempty"`

	// (Updatable) Retention period (in hours) for responses. The TTL starts from the time the response was created.
	ResponsesRetentionInHours *int64 `json:"responsesRetentionInHours,omitempty" tf:"responses_retention_in_hours,omitempty"`
}

type ConversationConfigParameters struct {

	// (Updatable) Retention period (in hours) for conversations. The TTL starts from the time the conversation was last updated.
	// +kubebuilder:validation:Optional
	ConversationsRetentionInHours *int64 `json:"conversationsRetentionInHours,omitempty" tf:"conversations_retention_in_hours,omitempty"`

	// (Updatable) Retention period (in hours) for responses. The TTL starts from the time the response was created.
	// +kubebuilder:validation:Optional
	ResponsesRetentionInHours *int64 `json:"responsesRetentionInHours,omitempty" tf:"responses_retention_in_hours,omitempty"`
}

type EmbeddingConfigInitParameters struct {

	// (Updatable) LLM selection configuration.
	LlmSelection []EmbeddingConfigLlmSelectionInitParameters `json:"llmSelection,omitempty" tf:"llm_selection,omitempty"`
}

type EmbeddingConfigLlmSelectionInitParameters struct {

	// (Updatable) The type of LLM selection.
	LlmSelectionType *string `json:"llmSelectionType,omitempty" tf:"llm_selection_type,omitempty"`

	// (Updatable) The id of the GenAI model
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/generativeai/v1alpha1.Model
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`

	// Reference to a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDRef *v1.Reference `json:"modelIdRef,omitempty" tf:"-"`

	// Selector for a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDSelector *v1.Selector `json:"modelIdSelector,omitempty" tf:"-"`
}

type EmbeddingConfigLlmSelectionObservation struct {

	// (Updatable) The type of LLM selection.
	LlmSelectionType *string `json:"llmSelectionType,omitempty" tf:"llm_selection_type,omitempty"`

	// (Updatable) The id of the GenAI model
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`
}

type EmbeddingConfigLlmSelectionParameters struct {

	// (Updatable) The type of LLM selection.
	// +kubebuilder:validation:Optional
	LlmSelectionType *string `json:"llmSelectionType" tf:"llm_selection_type,omitempty"`

	// (Updatable) The id of the GenAI model
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/generativeai/v1alpha1.Model
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`

	// Reference to a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDRef *v1.Reference `json:"modelIdRef,omitempty" tf:"-"`

	// Selector for a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDSelector *v1.Selector `json:"modelIdSelector,omitempty" tf:"-"`
}

type EmbeddingConfigObservation struct {

	// (Updatable) LLM selection configuration.
	LlmSelection []EmbeddingConfigLlmSelectionObservation `json:"llmSelection,omitempty" tf:"llm_selection,omitempty"`
}

type EmbeddingConfigParameters struct {

	// (Updatable) LLM selection configuration.
	// +kubebuilder:validation:Optional
	LlmSelection []EmbeddingConfigLlmSelectionParameters `json:"llmSelection" tf:"llm_selection,omitempty"`
}

type ExtractionConfigInitParameters struct {

	// (Updatable) LLM selection configuration.
	LlmSelection []ExtractionConfigLlmSelectionInitParameters `json:"llmSelection,omitempty" tf:"llm_selection,omitempty"`
}

type ExtractionConfigLlmSelectionInitParameters struct {

	// (Updatable) The type of LLM selection.
	LlmSelectionType *string `json:"llmSelectionType,omitempty" tf:"llm_selection_type,omitempty"`

	// (Updatable) The id of the GenAI model
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/generativeai/v1alpha1.Model
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`

	// Reference to a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDRef *v1.Reference `json:"modelIdRef,omitempty" tf:"-"`

	// Selector for a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDSelector *v1.Selector `json:"modelIdSelector,omitempty" tf:"-"`
}

type ExtractionConfigLlmSelectionObservation struct {

	// (Updatable) The type of LLM selection.
	LlmSelectionType *string `json:"llmSelectionType,omitempty" tf:"llm_selection_type,omitempty"`

	// (Updatable) The id of the GenAI model
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`
}

type ExtractionConfigLlmSelectionParameters struct {

	// (Updatable) The type of LLM selection.
	// +kubebuilder:validation:Optional
	LlmSelectionType *string `json:"llmSelectionType" tf:"llm_selection_type,omitempty"`

	// (Updatable) The id of the GenAI model
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/generativeai/v1alpha1.Model
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`

	// Reference to a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDRef *v1.Reference `json:"modelIdRef,omitempty" tf:"-"`

	// Selector for a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDSelector *v1.Selector `json:"modelIdSelector,omitempty" tf:"-"`
}

type ExtractionConfigObservation struct {

	// (Updatable) LLM selection configuration.
	LlmSelection []ExtractionConfigLlmSelectionObservation `json:"llmSelection,omitempty" tf:"llm_selection,omitempty"`
}

type ExtractionConfigParameters struct {

	// (Updatable) LLM selection configuration.
	// +kubebuilder:validation:Optional
	LlmSelection []ExtractionConfigLlmSelectionParameters `json:"llmSelection" tf:"llm_selection,omitempty"`
}

type LongTermMemoryConfigInitParameters struct {

	// (Updatable) Standard strategy settings for long-term memory.
	StandardLongTermMemoryStrategy []StandardLongTermMemoryStrategyInitParameters `json:"standardLongTermMemoryStrategy,omitempty" tf:"standard_long_term_memory_strategy,omitempty"`
}

type LongTermMemoryConfigObservation struct {

	// (Updatable) Standard strategy settings for long-term memory.
	StandardLongTermMemoryStrategy []StandardLongTermMemoryStrategyObservation `json:"standardLongTermMemoryStrategy,omitempty" tf:"standard_long_term_memory_strategy,omitempty"`
}

type LongTermMemoryConfigParameters struct {

	// (Updatable) Standard strategy settings for long-term memory.
	// +kubebuilder:validation:Optional
	StandardLongTermMemoryStrategy []StandardLongTermMemoryStrategyParameters `json:"standardLongTermMemoryStrategy,omitempty" tf:"standard_long_term_memory_strategy,omitempty"`
}

type ProjectInitParameters struct {

	// (Updatable) Owning compartment OCID for a GenerativeAiProject.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Holds configuration related to conversation retention
	ConversationConfig []ConversationConfigInitParameters `json:"conversationConfig,omitempty" tf:"conversation_config,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	DefinedTags map[string]string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) An optional description of the GenerativeAiProject.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	FreeformTags map[string]string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Configuration settings for long-term memory behavior.
	LongTermMemoryConfig []LongTermMemoryConfigInitParameters `json:"longTermMemoryConfig,omitempty" tf:"long_term_memory_config,omitempty"`

	// (Updatable) Configuration settings for short-term memory optimization.
	ShortTermMemoryOptimizationConfig []ShortTermMemoryOptimizationConfigInitParameters `json:"shortTermMemoryOptimizationConfig,omitempty" tf:"short_term_memory_optimization_config,omitempty"`
}

type ProjectObservation struct {

	// (Updatable) Owning compartment OCID for a GenerativeAiProject.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Holds configuration related to conversation retention
	ConversationConfig []ConversationConfigObservation `json:"conversationConfig,omitempty" tf:"conversation_config,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	DefinedTags map[string]string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) An optional description of the GenerativeAiProject.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	FreeformTags map[string]string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// An OCID that uniquely identifies a GenerativeAiProject.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A message describing the current state in more detail that can provide actionable information.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// (Updatable) Configuration settings for long-term memory behavior.
	LongTermMemoryConfig []LongTermMemoryConfigObservation `json:"longTermMemoryConfig,omitempty" tf:"long_term_memory_config,omitempty"`

	// (Updatable) Configuration settings for short-term memory optimization.
	ShortTermMemoryOptimizationConfig []ShortTermMemoryOptimizationConfigObservation `json:"shortTermMemoryOptimizationConfig,omitempty" tf:"short_term_memory_optimization_config,omitempty"`

	// The lifecycle state of a GenerativeAiProject.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace.  Example: {"orcl-cloud.free-tier-retained": "true"}
	SystemTags map[string]string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The date and time that the generativeAiProject was created in the format of an RFC3339 datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The date and time that the generativeAiProject was updated in the format of an RFC3339 datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type ProjectParameters struct {

	// (Updatable) Owning compartment OCID for a GenerativeAiProject.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Holds configuration related to conversation retention
	// +kubebuilder:validation:Optional
	ConversationConfig []ConversationConfigParameters `json:"conversationConfig,omitempty" tf:"conversation_config,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	DefinedTags map[string]string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) An optional description of the GenerativeAiProject.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Configuration settings for long-term memory behavior.
	// +kubebuilder:validation:Optional
	LongTermMemoryConfig []LongTermMemoryConfigParameters `json:"longTermMemoryConfig,omitempty" tf:"long_term_memory_config,omitempty"`

	// (Updatable) Configuration settings for short-term memory optimization.
	// +kubebuilder:validation:Optional
	ShortTermMemoryOptimizationConfig []ShortTermMemoryOptimizationConfigParameters `json:"shortTermMemoryOptimizationConfig,omitempty" tf:"short_term_memory_optimization_config,omitempty"`
}

type ShortTermMemoryOptimizationConfigInitParameters struct {

	// (Updatable) Configuration for condensing conversation content.
	CondenserConfig []CondenserConfigInitParameters `json:"condenserConfig,omitempty" tf:"condenser_config,omitempty"`

	// (Updatable) Indicates whether long-term memory is enabled.
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`
}

type ShortTermMemoryOptimizationConfigObservation struct {

	// (Updatable) Configuration for condensing conversation content.
	CondenserConfig []CondenserConfigObservation `json:"condenserConfig,omitempty" tf:"condenser_config,omitempty"`

	// (Updatable) Indicates whether long-term memory is enabled.
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`
}

type ShortTermMemoryOptimizationConfigParameters struct {

	// (Updatable) Configuration for condensing conversation content.
	// +kubebuilder:validation:Optional
	CondenserConfig []CondenserConfigParameters `json:"condenserConfig,omitempty" tf:"condenser_config,omitempty"`

	// (Updatable) Indicates whether long-term memory is enabled.
	// +kubebuilder:validation:Optional
	IsEnabled *bool `json:"isEnabled" tf:"is_enabled,omitempty"`
}

type StandardLongTermMemoryStrategyInitParameters struct {

	// (Updatable) Configuration for generating embeddings from extracted information.
	EmbeddingConfig []EmbeddingConfigInitParameters `json:"embeddingConfig,omitempty" tf:"embedding_config,omitempty"`

	// (Updatable) Configuration for information extraction from conversation content.
	ExtractionConfig []ExtractionConfigInitParameters `json:"extractionConfig,omitempty" tf:"extraction_config,omitempty"`

	// (Updatable) Indicates whether long-term memory is enabled.
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`
}

type StandardLongTermMemoryStrategyObservation struct {

	// (Updatable) Configuration for generating embeddings from extracted information.
	EmbeddingConfig []EmbeddingConfigObservation `json:"embeddingConfig,omitempty" tf:"embedding_config,omitempty"`

	// (Updatable) Configuration for information extraction from conversation content.
	ExtractionConfig []ExtractionConfigObservation `json:"extractionConfig,omitempty" tf:"extraction_config,omitempty"`

	// (Updatable) Indicates whether long-term memory is enabled.
	IsEnabled *bool `json:"isEnabled,omitempty" tf:"is_enabled,omitempty"`
}

type StandardLongTermMemoryStrategyParameters struct {

	// (Updatable) Configuration for generating embeddings from extracted information.
	// +kubebuilder:validation:Optional
	EmbeddingConfig []EmbeddingConfigParameters `json:"embeddingConfig,omitempty" tf:"embedding_config,omitempty"`

	// (Updatable) Configuration for information extraction from conversation content.
	// +kubebuilder:validation:Optional
	ExtractionConfig []ExtractionConfigParameters `json:"extractionConfig,omitempty" tf:"extraction_config,omitempty"`

	// (Updatable) Indicates whether long-term memory is enabled.
	// +kubebuilder:validation:Optional
	IsEnabled *bool `json:"isEnabled" tf:"is_enabled,omitempty"`
}

// ProjectSpec defines the desired state of Project
type ProjectSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProjectParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectInitParameters `json:"initProvider,omitempty"`
}

// ProjectStatus defines the observed state of Project.
type ProjectStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Project is the Schema for the Projects API. Provides the Project resource in Oracle Cloud Infrastructure Generative AI service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type Project struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ProjectSpec   `json:"spec"`
	Status            ProjectStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectList contains a list of Projects
type ProjectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Project `json:"items"`
}

// Repository type metadata.
var (
	Project_Kind             = "Project"
	Project_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Project_Kind}.String()
	Project_KindAPIVersion   = Project_Kind + "." + CRDGroupVersion.String()
	Project_GroupVersionKind = CRDGroupVersion.WithKind(Project_Kind)
)

func init() {
	SchemeBuilder.Register(&Project{}, &ProjectList{})
}
