apiVersion: cloudbridge.oci.upbound.io/v1alpha1
kind: Asset
metadata:
  annotations:
    meta.upbound.io/example-id: cloudbridge/v1alpha1/asset
  labels:
    testing.upbound.io/example-name: test_asset
  name: test-asset
spec:
  forProvider:
    assetClassName: ${var.asset_asset_class_name}
    assetClassVersion: ${var.asset_asset_class_version}
    assetDetails: ${var.asset_asset_details}
    assetSourceIds: ${var.asset_asset_source_ids}
    assetType: ${var.asset_asset_type}
    attachedEbsVolumesCost:
    - amount: ${var.asset_attached_ebs_volumes_cost_amount}
      currencyCode: ${var.asset_attached_ebs_volumes_cost_currency_code}
    awsEbs:
    - attachments:
      - device: ${var.asset_aws_ebs_attachments_device}
        instanceKey: ${var.asset_aws_ebs_attachments_instance_key}
        isDeleteOnTermination: ${var.asset_aws_ebs_attachments_is_delete_on_termination}
        status: ${var.asset_aws_ebs_attachments_status}
        volumeKey: ${var.asset_aws_ebs_attachments_volume_key}
      availabilityZone: ${var.asset_aws_ebs_availability_zone}
      iops: ${var.asset_aws_ebs_iops}
      isEncrypted: ${var.asset_aws_ebs_is_encrypted}
      isMultiAttachEnabled: ${var.asset_aws_ebs_is_multi_attach_enabled}
      sizeInGiBs: ${var.asset_aws_ebs_size_in_gi_bs}
      status: ${var.asset_aws_ebs_status}
      tags:
      - key: ${var.asset_aws_ebs_tags_key}
        value: ${var.asset_aws_ebs_tags_value}
      throughput: ${var.asset_aws_ebs_throughput}
      volumeKey: ${var.asset_aws_ebs_volume_key}
      volumeType: ${var.asset_aws_ebs_volume_type}
    awsEc2:
    - architecture: ${var.asset_aws_ec2_architecture}
      areElasticInferenceAcceleratorsPresent: ${var.asset_aws_ec2_are_elastic_inference_accelerators_present}
      bootMode: ${var.asset_aws_ec2_boot_mode}
      capacityReservationKey: ${var.asset_aws_ec2_capacity_reservation_key}
      imageKey: ${var.asset_aws_ec2_image_key}
      instanceKey: ${var.asset_aws_ec2_instance_key}
      instanceLifecycle: ${var.asset_aws_ec2_instance_lifecycle}
      instanceType: ${var.asset_aws_ec2_instance_type}
      ipAddress: ${var.asset_aws_ec2_ip_address}
      ipv6address: ${var.asset_aws_ec2_ipv6address}
      isEnclaveOptions: ${var.asset_aws_ec2_is_enclave_options}
      isHibernationOptions: ${var.asset_aws_ec2_is_hibernation_options}
      isSourceDestCheck: ${var.asset_aws_ec2_is_source_dest_check}
      isSpotInstance: ${var.asset_aws_ec2_is_spot_instance}
      kernelKey: ${var.asset_aws_ec2_kernel_key}
      licenses: ${var.asset_aws_ec2_licenses}
      maintenanceOptions: ${var.asset_aws_ec2_maintenance_options}
      monitoring: ${var.asset_aws_ec2_monitoring}
      networkInterfaces:
      - association:
        - carrierIp: ${var.asset_aws_ec2_network_interfaces_association_carrier_ip}
          customerOwnedIp: ${var.asset_aws_ec2_network_interfaces_association_customer_owned_ip}
          ipOwnerKey: ${var.asset_aws_ec2_network_interfaces_association_ip_owner_key}
          publicDnsName: ${var.asset_aws_ec2_network_interfaces_association_public_dns_name}
          publicIp: ${var.asset_aws_ec2_network_interfaces_association_public_ip}
        attachment:
        - attachmentKey: ${var.asset_aws_ec2_network_interfaces_attachment_attachment_key}
          deviceIndex: ${var.asset_aws_ec2_network_interfaces_attachment_device_index}
          isDeleteOnTermination: ${var.asset_aws_ec2_network_interfaces_attachment_is_delete_on_termination}
          networkCardIndex: ${var.asset_aws_ec2_network_interfaces_attachment_network_card_index}
          status: ${var.asset_aws_ec2_network_interfaces_attachment_status}
          timeAttach: ${var.asset_aws_ec2_network_interfaces_attachment_time_attach}
        description: ${var.asset_aws_ec2_network_interfaces_description}
        interfaceType: ${var.asset_aws_ec2_network_interfaces_interface_type}
        ipv4prefixes: ${var.asset_aws_ec2_network_interfaces_ipv4prefixes}
        ipv6addresses: ${var.asset_aws_ec2_network_interfaces_ipv6addresses}
        ipv6prefixes: ${var.asset_aws_ec2_network_interfaces_ipv6prefixes}
        isSourceDestCheck: ${var.asset_aws_ec2_network_interfaces_is_source_dest_check}
        macAddress: ${var.asset_aws_ec2_network_interfaces_mac_address}
        networkInterfaceKey: ${var.asset_aws_ec2_network_interfaces_network_interface_key}
        ownerKey: ${var.asset_aws_ec2_network_interfaces_owner_key}
        privateIpAddresses:
        - association:
          - carrierIp: ${var.asset_aws_ec2_network_interfaces_private_ip_addresses_association_carrier_ip}
            customerOwnedIp: ${var.asset_aws_ec2_network_interfaces_private_ip_addresses_association_customer_owned_ip}
            ipOwnerKey: ${var.asset_aws_ec2_network_interfaces_private_ip_addresses_association_ip_owner_key}
            publicDnsName: ${var.asset_aws_ec2_network_interfaces_private_ip_addresses_association_public_dns_name}
            publicIp: ${var.asset_aws_ec2_network_interfaces_private_ip_addresses_association_public_ip}
          isPrimary: ${var.asset_aws_ec2_network_interfaces_private_ip_addresses_is_primary}
          privateDnsName: ${var.asset_aws_ec2_network_interfaces_private_ip_addresses_private_dns_name}
          privateIpAddress: ${var.asset_aws_ec2_network_interfaces_private_ip_addresses_private_ip_address}
        securityGroups:
        - groupKey: ${var.asset_aws_ec2_network_interfaces_security_groups_group_key}
          groupNameSelector:
            matchLabels:
              testing.upbound.io/example-name: test_group
        status: ${var.asset_aws_ec2_network_interfaces_status}
        subnetKey: ${var.asset_aws_ec2_network_interfaces_subnet_key}
      placement:
      - affinity: ${var.asset_aws_ec2_placement_affinity}
        availabilityZone: ${var.asset_aws_ec2_placement_availability_zone}
        groupNameSelector:
          matchLabels:
            testing.upbound.io/example-name: test_group
        hostKey: ${var.asset_aws_ec2_placement_host_key}
        hostResourceGroupArn: ${var.asset_aws_ec2_placement_host_resource_group_arn}
        partitionNumber: ${var.asset_aws_ec2_placement_partition_number}
        spreadDomain: ${var.asset_aws_ec2_placement_spread_domain}
        tenancy: ${var.asset_aws_ec2_placement_tenancy}
      privateDnsName: ${var.asset_aws_ec2_private_dns_name}
      privateIpAddress: ${var.asset_aws_ec2_private_ip_address}
      rootDeviceName: ${var.asset_aws_ec2_root_device_name}
      rootDeviceType: ${var.asset_aws_ec2_root_device_type}
      securityGroups:
      - groupKey: ${var.asset_aws_ec2_security_groups_group_key}
        groupNameSelector:
          matchLabels:
            testing.upbound.io/example-name: test_group
      sriovNetSupport: ${var.asset_aws_ec2_sriov_net_support}
      state:
      - code: ${var.asset_aws_ec2_state_code}
        name: ${var.asset_aws_ec2_state_name}
      subnetKey: ${var.asset_aws_ec2_subnet_key}
      tags:
      - key: ${var.asset_aws_ec2_tags_key}
        value: ${var.asset_aws_ec2_tags_value}
      timeLaunch: ${var.asset_aws_ec2_time_launch}
      tpmSupport: ${var.asset_aws_ec2_tpm_support}
      virtualizationType: ${var.asset_aws_ec2_virtualization_type}
      vpcKey: ${var.asset_aws_ec2_vpc_key}
    awsEc2Cost:
    - amount: ${var.asset_aws_ec2cost_amount}
      currencyCode: ${var.asset_aws_ec2cost_currency_code}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    compute:
    - connectedNetworks: ${var.asset_compute_connected_networks}
      coresCount: ${var.asset_compute_cores_count}
      cpuModel: ${var.asset_compute_cpu_model}
      description: ${var.asset_compute_description}
      disks:
      - bootOrder: ${var.asset_compute_disks_boot_order}
        isCbtEnabled: ${var.asset_compute_disks_is_cbt_enabled}
        location: ${var.asset_compute_disks_location}
        name: ${var.asset_compute_disks_name}
        persistentMode: ${var.asset_compute_disks_persistent_mode}
        sizeInMbs: ${var.asset_compute_disks_size_in_mbs}
        uuid: ${var.asset_compute_disks_uuid}
        uuidLun: ${var.asset_compute_disks_uuid_lun}
      disksCount: ${var.asset_compute_disks_count}
      dnsName: ${var.asset_compute_dns_name}
      firmware: ${var.asset_compute_firmware}
      gpuDevices:
      - coresCount: ${var.asset_compute_gpu_devices_cores_count}
        description: ${var.asset_compute_gpu_devices_description}
        manufacturer: ${var.asset_compute_gpu_devices_manufacturer}
        memoryInMbs: ${var.asset_compute_gpu_devices_memory_in_mbs}
        name: ${var.asset_compute_gpu_devices_name}
      gpuDevicesCount: ${var.asset_compute_gpu_devices_count}
      guestState: ${var.asset_compute_guest_state}
      hardwareVersion: ${var.asset_compute_hardware_version}
      hostName: ${var.asset_compute_host_name}
      isPmemEnabled: ${var.asset_compute_is_pmem_enabled}
      isTpmEnabled: ${var.asset_compute_is_tpm_enabled}
      latencySensitivity: ${var.asset_compute_latency_sensitivity}
      memoryInMbs: ${var.asset_compute_memory_in_mbs}
      nics:
      - ipAddresses: ${var.asset_compute_nics_ip_addresses}
        label: ${var.asset_compute_nics_label}
        macAddress: ${var.asset_compute_nics_mac_address}
        macAddressType: ${var.asset_compute_nics_mac_address_type}
        networkName: ${var.asset_compute_nics_network_name}
        switchName: ${var.asset_compute_nics_switch_name}
      nicsCount: ${var.asset_compute_nics_count}
      nvdimmController:
      - busNumber: ${var.asset_compute_nvdimm_controller_bus_number}
        label: ${var.asset_compute_nvdimm_controller_label}
      nvdimms:
      - controllerKey: ${var.asset_compute_nvdimms_controller_key}
        label: ${var.asset_compute_nvdimms_label}
        unitNumber: ${var.asset_compute_nvdimms_unit_number}
      operatingSystem: ${var.asset_compute_operating_system}
      operatingSystemVersion: ${var.asset_compute_operating_system_version}
      pmemInMbs: ${var.asset_compute_pmem_in_mbs}
      powerState: ${var.asset_compute_power_state}
      primaryIp: ${var.asset_compute_primary_ip}
      scsiController:
      - label: ${var.asset_compute_scsi_controller_label}
        sharedBus: ${var.asset_compute_scsi_controller_shared_bus}
        unitNumber: ${var.asset_compute_scsi_controller_unit_number}
      storageProvisionedInMbs: ${var.asset_compute_storage_provisioned_in_mbs}
      threadsPerCoreCount: ${var.asset_compute_threads_per_core_count}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.asset_display_name}
    externalAssetKey: ${var.asset_external_asset_key}
    freeformTags:
      Department: Finance
    inventoryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_inventory
    sourceKey: ${var.asset_source_key}
    vm:
    - hypervisorHost: ${var.asset_vm_hypervisor_host}
      hypervisorVendor: ${var.asset_vm_hypervisor_vendor}
      hypervisorVersion: ${var.asset_vm_hypervisor_version}
    vmwareVcenter:
    - dataCenter: ${var.asset_vmware_vcenter_data_center}
      vcenterKey: ${var.asset_vmware_vcenter_vcenter_key}
      vcenterVersion: ${var.asset_vmware_vcenter_vcenter_version}
    vmwareVm:
    - cluster: ${var.asset_vmware_vm_cluster}
      customerFields: ${var.asset_vmware_vm_customer_fields}
      customerTags:
      - description: ${var.asset_vmware_vm_customer_tags_description}
        name: ${var.asset_vmware_vm_customer_tags_name}
      faultToleranceBandwidth: ${var.asset_vmware_vm_fault_tolerance_bandwidth}
      faultToleranceSecondaryLatency: ${var.asset_vmware_vm_fault_tolerance_secondary_latency}
      faultToleranceState: ${var.asset_vmware_vm_fault_tolerance_state}
      instanceUuid: ${var.asset_vmware_vm_instance_uuid}
      isDisksCbtEnabled: ${var.asset_vmware_vm_is_disks_cbt_enabled}
      isDisksUuidEnabled: ${var.asset_vmware_vm_is_disks_uuid_enabled}
      path: ${var.asset_vmware_vm_path}
      vmwareToolsStatus: ${var.asset_vmware_vm_vmware_tools_status}
