/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type OciCacheBackupInitParameters struct {

	// Specifies whether the backup was created from a replica or primary node
	BackupSource *string `json:"backupSource,omitempty" tf:"backup_source,omitempty"`

	// (Updatable) Compartment identifier
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Backup description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) Backup display name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) An optional property when incremented triggers Export To Object Storage. Could be set to any integer value.
	ExportToObjectStorageTrigger *float64 `json:"exportToObjectStorageTrigger,omitempty" tf:"export_to_object_storage_trigger,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Backup retention period in days.
	RetentionPeriodInDays *float64 `json:"retentionPeriodInDays,omitempty" tf:"retention_period_in_days,omitempty"`

	// Oracle Cloud Infrastructure Cache cluster identifier
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/redis/v1alpha1.RedisCluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	SourceClusterID *string `json:"sourceClusterId,omitempty" tf:"source_cluster_id,omitempty"`

	// Reference to a RedisCluster in redis to populate sourceClusterId.
	// +kubebuilder:validation:Optional
	SourceClusterIDRef *v1.Reference `json:"sourceClusterIdRef,omitempty" tf:"-"`

	// Selector for a RedisCluster in redis to populate sourceClusterId.
	// +kubebuilder:validation:Optional
	SourceClusterIDSelector *v1.Selector `json:"sourceClusterIdSelector,omitempty" tf:"-"`
}

type OciCacheBackupObservation struct {

	// Backup size in GB.
	BackupSizeInGbs *float64 `json:"backupSizeInGbs,omitempty" tf:"backup_size_in_gbs,omitempty"`

	// Specifies whether the backup was created from a replica or primary node
	BackupSource *string `json:"backupSource,omitempty" tf:"backup_source,omitempty"`

	// Backup Type.
	BackupType *string `json:"backupType,omitempty" tf:"backup_type,omitempty"`

	// The amount of memory allocated to the cluster, in gigabytes.
	ClusterMemoryInGbs *float64 `json:"clusterMemoryInGbs,omitempty" tf:"cluster_memory_in_gbs,omitempty"`

	// Specifies whether the cluster is sharded or non-sharded.
	ClusterMode *string `json:"clusterMode,omitempty" tf:"cluster_mode,omitempty"`

	// (Updatable) Compartment identifier
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Backup description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) Backup display name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) An optional property when incremented triggers Export To Object Storage. Could be set to any integer value.
	ExportToObjectStorageTrigger *float64 `json:"exportToObjectStorageTrigger,omitempty" tf:"export_to_object_storage_trigger,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// Unique identifier that is immutable on creation
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) Backup retention period in days.
	RetentionPeriodInDays *float64 `json:"retentionPeriodInDays,omitempty" tf:"retention_period_in_days,omitempty"`

	// The number of shards in a sharded cluster. Only applicable when clusterMode is SHARDED.
	ShardCount *float64 `json:"shardCount,omitempty" tf:"shard_count,omitempty"`

	// The Oracle Cloud Infrastructure Cache engine version that the cluster is running.
	SoftwareVersion *string `json:"softwareVersion,omitempty" tf:"software_version,omitempty"`

	// Oracle Cloud Infrastructure Cache cluster identifier
	SourceClusterID *string `json:"sourceClusterId,omitempty" tf:"source_cluster_id,omitempty"`

	// The current state of the backup.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Usage of system tag keys. These predefined keys are scoped to namespaces. Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The date and time the backup was created. An RFC3339 formatted datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The date and time the backup was updated. An RFC3339 formatted datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type OciCacheBackupParameters struct {

	// Specifies whether the backup was created from a replica or primary node
	// +kubebuilder:validation:Optional
	BackupSource *string `json:"backupSource,omitempty" tf:"backup_source,omitempty"`

	// (Updatable) Compartment identifier
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Backup description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) Backup display name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) An optional property when incremented triggers Export To Object Storage. Could be set to any integer value.
	// +kubebuilder:validation:Optional
	ExportToObjectStorageTrigger *float64 `json:"exportToObjectStorageTrigger,omitempty" tf:"export_to_object_storage_trigger,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Backup retention period in days.
	// +kubebuilder:validation:Optional
	RetentionPeriodInDays *float64 `json:"retentionPeriodInDays,omitempty" tf:"retention_period_in_days,omitempty"`

	// Oracle Cloud Infrastructure Cache cluster identifier
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/redis/v1alpha1.RedisCluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	SourceClusterID *string `json:"sourceClusterId,omitempty" tf:"source_cluster_id,omitempty"`

	// Reference to a RedisCluster in redis to populate sourceClusterId.
	// +kubebuilder:validation:Optional
	SourceClusterIDRef *v1.Reference `json:"sourceClusterIdRef,omitempty" tf:"-"`

	// Selector for a RedisCluster in redis to populate sourceClusterId.
	// +kubebuilder:validation:Optional
	SourceClusterIDSelector *v1.Selector `json:"sourceClusterIdSelector,omitempty" tf:"-"`
}

// OciCacheBackupSpec defines the desired state of OciCacheBackup
type OciCacheBackupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OciCacheBackupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OciCacheBackupInitParameters `json:"initProvider,omitempty"`
}

// OciCacheBackupStatus defines the observed state of OciCacheBackup.
type OciCacheBackupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OciCacheBackupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OciCacheBackup is the Schema for the OciCacheBackups API. Provides the Oci Cache Backup resource in Oracle Cloud Infrastructure Redis service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type OciCacheBackup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   OciCacheBackupSpec   `json:"spec"`
	Status OciCacheBackupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OciCacheBackupList contains a list of OciCacheBackups
type OciCacheBackupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OciCacheBackup `json:"items"`
}

// Repository type metadata.
var (
	OciCacheBackup_Kind             = "OciCacheBackup"
	OciCacheBackup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OciCacheBackup_Kind}.String()
	OciCacheBackup_KindAPIVersion   = OciCacheBackup_Kind + "." + CRDGroupVersion.String()
	OciCacheBackup_GroupVersionKind = CRDGroupVersion.WithKind(OciCacheBackup_Kind)
)

func init() {
	SchemeBuilder.Register(&OciCacheBackup{}, &OciCacheBackupList{})
}
