/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DynamicSetRemovePackagesManagementInitParameters struct {

	// The OCID of the dynamic set. This filter returns resources associated with this dynamic set.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/osmanagementhub/v1alpha1.DynamicSet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DynamicSetID *string `json:"dynamicSetId,omitempty" tf:"dynamic_set_id,omitempty"`

	// Reference to a DynamicSet in osmanagementhub to populate dynamicSetId.
	// +kubebuilder:validation:Optional
	DynamicSetIDRef *v1.NamespacedReference `json:"dynamicSetIdRef,omitempty" tf:"-"`

	// Selector for a DynamicSet in osmanagementhub to populate dynamicSetId.
	// +kubebuilder:validation:Optional
	DynamicSetIDSelector *v1.NamespacedSelector `json:"dynamicSetIdSelector,omitempty" tf:"-"`

	// The list of managed instance OCIDs to be attached/detached.
	ManagedInstances []*string `json:"managedInstances,omitempty" tf:"managed_instances,omitempty"`

	// The list of package names.
	PackageNames []*string `json:"packageNames,omitempty" tf:"package_names,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []DynamicSetRemovePackagesManagementWorkRequestDetailsInitParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type DynamicSetRemovePackagesManagementObservation struct {

	// The OCID of the dynamic set. This filter returns resources associated with this dynamic set.
	DynamicSetID *string `json:"dynamicSetId,omitempty" tf:"dynamic_set_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The list of managed instance OCIDs to be attached/detached.
	ManagedInstances []*string `json:"managedInstances,omitempty" tf:"managed_instances,omitempty"`

	// The list of package names.
	PackageNames []*string `json:"packageNames,omitempty" tf:"package_names,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []DynamicSetRemovePackagesManagementWorkRequestDetailsObservation `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type DynamicSetRemovePackagesManagementParameters struct {

	// The OCID of the dynamic set. This filter returns resources associated with this dynamic set.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/osmanagementhub/v1alpha1.DynamicSet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DynamicSetID *string `json:"dynamicSetId,omitempty" tf:"dynamic_set_id,omitempty"`

	// Reference to a DynamicSet in osmanagementhub to populate dynamicSetId.
	// +kubebuilder:validation:Optional
	DynamicSetIDRef *v1.NamespacedReference `json:"dynamicSetIdRef,omitempty" tf:"-"`

	// Selector for a DynamicSet in osmanagementhub to populate dynamicSetId.
	// +kubebuilder:validation:Optional
	DynamicSetIDSelector *v1.NamespacedSelector `json:"dynamicSetIdSelector,omitempty" tf:"-"`

	// The list of managed instance OCIDs to be attached/detached.
	// +kubebuilder:validation:Optional
	ManagedInstances []*string `json:"managedInstances,omitempty" tf:"managed_instances,omitempty"`

	// The list of package names.
	// +kubebuilder:validation:Optional
	PackageNames []*string `json:"packageNames,omitempty" tf:"package_names,omitempty"`

	// Provides the name and description of the job.
	// +kubebuilder:validation:Optional
	WorkRequestDetails []DynamicSetRemovePackagesManagementWorkRequestDetailsParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type DynamicSetRemovePackagesManagementWorkRequestDetailsInitParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type DynamicSetRemovePackagesManagementWorkRequestDetailsObservation struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type DynamicSetRemovePackagesManagementWorkRequestDetailsParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

// DynamicSetRemovePackagesManagementSpec defines the desired state of DynamicSetRemovePackagesManagement
type DynamicSetRemovePackagesManagementSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DynamicSetRemovePackagesManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DynamicSetRemovePackagesManagementInitParameters `json:"initProvider,omitempty"`
}

// DynamicSetRemovePackagesManagementStatus defines the observed state of DynamicSetRemovePackagesManagement.
type DynamicSetRemovePackagesManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DynamicSetRemovePackagesManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DynamicSetRemovePackagesManagement is the Schema for the DynamicSetRemovePackagesManagements API. Provides the Dynamic Set Remove Packages Management resource in Oracle Cloud Infrastructure Os Management Hub service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type DynamicSetRemovePackagesManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.packageNames) || (has(self.initProvider) && has(self.initProvider.packageNames))",message="spec.forProvider.packageNames is a required parameter"
	Spec   DynamicSetRemovePackagesManagementSpec   `json:"spec"`
	Status DynamicSetRemovePackagesManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DynamicSetRemovePackagesManagementList contains a list of DynamicSetRemovePackagesManagements
type DynamicSetRemovePackagesManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DynamicSetRemovePackagesManagement `json:"items"`
}

// Repository type metadata.
var (
	DynamicSetRemovePackagesManagement_Kind             = "DynamicSetRemovePackagesManagement"
	DynamicSetRemovePackagesManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DynamicSetRemovePackagesManagement_Kind}.String()
	DynamicSetRemovePackagesManagement_KindAPIVersion   = DynamicSetRemovePackagesManagement_Kind + "." + CRDGroupVersion.String()
	DynamicSetRemovePackagesManagement_GroupVersionKind = CRDGroupVersion.WithKind(DynamicSetRemovePackagesManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&DynamicSetRemovePackagesManagement{}, &DynamicSetRemovePackagesManagementList{})
}
