/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ManagedInstanceInstallPackagesManagementInitParameters struct {

	// The OCID of the managed instance.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/osmanagementhub/v1alpha1.ManagedInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ManagedInstanceID *string `json:"managedInstanceId,omitempty" tf:"managed_instance_id,omitempty"`

	// Reference to a ManagedInstance in osmanagementhub to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDRef *v1.NamespacedReference `json:"managedInstanceIdRef,omitempty" tf:"-"`

	// Selector for a ManagedInstance in osmanagementhub to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDSelector *v1.NamespacedSelector `json:"managedInstanceIdSelector,omitempty" tf:"-"`

	// The list of package names.
	PackageNames []*string `json:"packageNames,omitempty" tf:"package_names,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []ManagedInstanceInstallPackagesManagementWorkRequestDetailsInitParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagedInstanceInstallPackagesManagementObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the managed instance.
	ManagedInstanceID *string `json:"managedInstanceId,omitempty" tf:"managed_instance_id,omitempty"`

	// The list of package names.
	PackageNames []*string `json:"packageNames,omitempty" tf:"package_names,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []ManagedInstanceInstallPackagesManagementWorkRequestDetailsObservation `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagedInstanceInstallPackagesManagementParameters struct {

	// The OCID of the managed instance.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/osmanagementhub/v1alpha1.ManagedInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ManagedInstanceID *string `json:"managedInstanceId,omitempty" tf:"managed_instance_id,omitempty"`

	// Reference to a ManagedInstance in osmanagementhub to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDRef *v1.NamespacedReference `json:"managedInstanceIdRef,omitempty" tf:"-"`

	// Selector for a ManagedInstance in osmanagementhub to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDSelector *v1.NamespacedSelector `json:"managedInstanceIdSelector,omitempty" tf:"-"`

	// The list of package names.
	// +kubebuilder:validation:Optional
	PackageNames []*string `json:"packageNames,omitempty" tf:"package_names,omitempty"`

	// Provides the name and description of the job.
	// +kubebuilder:validation:Optional
	WorkRequestDetails []ManagedInstanceInstallPackagesManagementWorkRequestDetailsParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagedInstanceInstallPackagesManagementWorkRequestDetailsInitParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type ManagedInstanceInstallPackagesManagementWorkRequestDetailsObservation struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type ManagedInstanceInstallPackagesManagementWorkRequestDetailsParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

// ManagedInstanceInstallPackagesManagementSpec defines the desired state of ManagedInstanceInstallPackagesManagement
type ManagedInstanceInstallPackagesManagementSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ManagedInstanceInstallPackagesManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ManagedInstanceInstallPackagesManagementInitParameters `json:"initProvider,omitempty"`
}

// ManagedInstanceInstallPackagesManagementStatus defines the observed state of ManagedInstanceInstallPackagesManagement.
type ManagedInstanceInstallPackagesManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ManagedInstanceInstallPackagesManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ManagedInstanceInstallPackagesManagement is the Schema for the ManagedInstanceInstallPackagesManagements API. Provides the Managed Instance Install Packages Management resource in Oracle Cloud Infrastructure Os Management Hub service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type ManagedInstanceInstallPackagesManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.packageNames) || (has(self.initProvider) && has(self.initProvider.packageNames))",message="spec.forProvider.packageNames is a required parameter"
	Spec   ManagedInstanceInstallPackagesManagementSpec   `json:"spec"`
	Status ManagedInstanceInstallPackagesManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ManagedInstanceInstallPackagesManagementList contains a list of ManagedInstanceInstallPackagesManagements
type ManagedInstanceInstallPackagesManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ManagedInstanceInstallPackagesManagement `json:"items"`
}

// Repository type metadata.
var (
	ManagedInstanceInstallPackagesManagement_Kind             = "ManagedInstanceInstallPackagesManagement"
	ManagedInstanceInstallPackagesManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ManagedInstanceInstallPackagesManagement_Kind}.String()
	ManagedInstanceInstallPackagesManagement_KindAPIVersion   = ManagedInstanceInstallPackagesManagement_Kind + "." + CRDGroupVersion.String()
	ManagedInstanceInstallPackagesManagement_GroupVersionKind = CRDGroupVersion.WithKind(ManagedInstanceInstallPackagesManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&ManagedInstanceInstallPackagesManagement{}, &ManagedInstanceInstallPackagesManagementList{})
}
