/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ManagedInstancesUpdatePackagesManagementInitParameters struct {

	// The OCID of the compartment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// The types of updates to be applied.
	UpdateTypes []*string `json:"updateTypes,omitempty" tf:"update_types,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []ManagedInstancesUpdatePackagesManagementWorkRequestDetailsInitParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagedInstancesUpdatePackagesManagementObservation struct {

	// The OCID of the compartment.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The types of updates to be applied.
	UpdateTypes []*string `json:"updateTypes,omitempty" tf:"update_types,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []ManagedInstancesUpdatePackagesManagementWorkRequestDetailsObservation `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagedInstancesUpdatePackagesManagementParameters struct {

	// The OCID of the compartment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// The types of updates to be applied.
	// +kubebuilder:validation:Optional
	UpdateTypes []*string `json:"updateTypes,omitempty" tf:"update_types,omitempty"`

	// Provides the name and description of the job.
	// +kubebuilder:validation:Optional
	WorkRequestDetails []ManagedInstancesUpdatePackagesManagementWorkRequestDetailsParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagedInstancesUpdatePackagesManagementWorkRequestDetailsInitParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type ManagedInstancesUpdatePackagesManagementWorkRequestDetailsObservation struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type ManagedInstancesUpdatePackagesManagementWorkRequestDetailsParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

// ManagedInstancesUpdatePackagesManagementSpec defines the desired state of ManagedInstancesUpdatePackagesManagement
type ManagedInstancesUpdatePackagesManagementSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ManagedInstancesUpdatePackagesManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ManagedInstancesUpdatePackagesManagementInitParameters `json:"initProvider,omitempty"`
}

// ManagedInstancesUpdatePackagesManagementStatus defines the observed state of ManagedInstancesUpdatePackagesManagement.
type ManagedInstancesUpdatePackagesManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ManagedInstancesUpdatePackagesManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ManagedInstancesUpdatePackagesManagement is the Schema for the ManagedInstancesUpdatePackagesManagements API. Provides the Managed Instances Update Packages Management resource in Oracle Cloud Infrastructure Os Management Hub service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type ManagedInstancesUpdatePackagesManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ManagedInstancesUpdatePackagesManagementSpec   `json:"spec"`
	Status            ManagedInstancesUpdatePackagesManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ManagedInstancesUpdatePackagesManagementList contains a list of ManagedInstancesUpdatePackagesManagements
type ManagedInstancesUpdatePackagesManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ManagedInstancesUpdatePackagesManagement `json:"items"`
}

// Repository type metadata.
var (
	ManagedInstancesUpdatePackagesManagement_Kind             = "ManagedInstancesUpdatePackagesManagement"
	ManagedInstancesUpdatePackagesManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ManagedInstancesUpdatePackagesManagement_Kind}.String()
	ManagedInstancesUpdatePackagesManagement_KindAPIVersion   = ManagedInstancesUpdatePackagesManagement_Kind + "." + CRDGroupVersion.String()
	ManagedInstancesUpdatePackagesManagement_GroupVersionKind = CRDGroupVersion.WithKind(ManagedInstancesUpdatePackagesManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&ManagedInstancesUpdatePackagesManagement{}, &ManagedInstancesUpdatePackagesManagementList{})
}
