/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ManagedInstanceDetachSoftwareSourcesManagementInitParameters struct {

	// The OCID of the managed instance.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/osmanagementhub/v1alpha1.ManagedInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ManagedInstanceID *string `json:"managedInstanceId,omitempty" tf:"managed_instance_id,omitempty"`

	// Reference to a ManagedInstance in osmanagementhub to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDRef *v1.NamespacedReference `json:"managedInstanceIdRef,omitempty" tf:"-"`

	// Selector for a ManagedInstance in osmanagementhub to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDSelector *v1.NamespacedSelector `json:"managedInstanceIdSelector,omitempty" tf:"-"`

	// The list of software source OCIDs to be attached/detached.
	SoftwareSources []*string `json:"softwareSources,omitempty" tf:"software_sources,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []ManagedInstanceDetachSoftwareSourcesManagementWorkRequestDetailsInitParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagedInstanceDetachSoftwareSourcesManagementObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the managed instance.
	ManagedInstanceID *string `json:"managedInstanceId,omitempty" tf:"managed_instance_id,omitempty"`

	// The list of software source OCIDs to be attached/detached.
	SoftwareSources []*string `json:"softwareSources,omitempty" tf:"software_sources,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []ManagedInstanceDetachSoftwareSourcesManagementWorkRequestDetailsObservation `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagedInstanceDetachSoftwareSourcesManagementParameters struct {

	// The OCID of the managed instance.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/osmanagementhub/v1alpha1.ManagedInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ManagedInstanceID *string `json:"managedInstanceId,omitempty" tf:"managed_instance_id,omitempty"`

	// Reference to a ManagedInstance in osmanagementhub to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDRef *v1.NamespacedReference `json:"managedInstanceIdRef,omitempty" tf:"-"`

	// Selector for a ManagedInstance in osmanagementhub to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDSelector *v1.NamespacedSelector `json:"managedInstanceIdSelector,omitempty" tf:"-"`

	// The list of software source OCIDs to be attached/detached.
	// +kubebuilder:validation:Optional
	SoftwareSources []*string `json:"softwareSources,omitempty" tf:"software_sources,omitempty"`

	// Provides the name and description of the job.
	// +kubebuilder:validation:Optional
	WorkRequestDetails []ManagedInstanceDetachSoftwareSourcesManagementWorkRequestDetailsParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagedInstanceDetachSoftwareSourcesManagementWorkRequestDetailsInitParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type ManagedInstanceDetachSoftwareSourcesManagementWorkRequestDetailsObservation struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type ManagedInstanceDetachSoftwareSourcesManagementWorkRequestDetailsParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

// ManagedInstanceDetachSoftwareSourcesManagementSpec defines the desired state of ManagedInstanceDetachSoftwareSourcesManagement
type ManagedInstanceDetachSoftwareSourcesManagementSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ManagedInstanceDetachSoftwareSourcesManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ManagedInstanceDetachSoftwareSourcesManagementInitParameters `json:"initProvider,omitempty"`
}

// ManagedInstanceDetachSoftwareSourcesManagementStatus defines the observed state of ManagedInstanceDetachSoftwareSourcesManagement.
type ManagedInstanceDetachSoftwareSourcesManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ManagedInstanceDetachSoftwareSourcesManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ManagedInstanceDetachSoftwareSourcesManagement is the Schema for the ManagedInstanceDetachSoftwareSourcesManagements API. Provides the Managed Instance Detach Software Sources Management resource in Oracle Cloud Infrastructure Os Management Hub service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type ManagedInstanceDetachSoftwareSourcesManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.softwareSources) || (has(self.initProvider) && has(self.initProvider.softwareSources))",message="spec.forProvider.softwareSources is a required parameter"
	Spec   ManagedInstanceDetachSoftwareSourcesManagementSpec   `json:"spec"`
	Status ManagedInstanceDetachSoftwareSourcesManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ManagedInstanceDetachSoftwareSourcesManagementList contains a list of ManagedInstanceDetachSoftwareSourcesManagements
type ManagedInstanceDetachSoftwareSourcesManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ManagedInstanceDetachSoftwareSourcesManagement `json:"items"`
}

// Repository type metadata.
var (
	ManagedInstanceDetachSoftwareSourcesManagement_Kind             = "ManagedInstanceDetachSoftwareSourcesManagement"
	ManagedInstanceDetachSoftwareSourcesManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ManagedInstanceDetachSoftwareSourcesManagement_Kind}.String()
	ManagedInstanceDetachSoftwareSourcesManagement_KindAPIVersion   = ManagedInstanceDetachSoftwareSourcesManagement_Kind + "." + CRDGroupVersion.String()
	ManagedInstanceDetachSoftwareSourcesManagement_GroupVersionKind = CRDGroupVersion.WithKind(ManagedInstanceDetachSoftwareSourcesManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&ManagedInstanceDetachSoftwareSourcesManagement{}, &ManagedInstanceDetachSoftwareSourcesManagementList{})
}
