/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ByolAllocationInitParameters struct {

	// (Updatable) The quantity of licensed units that allocated to this region.
	AllocatedUnits *float64 `json:"allocatedUnits,omitempty" tf:"allocated_units,omitempty"`

	// The OCID of the BYOL resource from which this BYOL Allocation is derived.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/ocvp/v1alpha1.Byol
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ByolID *string `json:"byolId,omitempty" tf:"byol_id,omitempty"`

	// Reference to a Byol in ocvp to populate byolId.
	// +kubebuilder:validation:Optional
	ByolIDRef *v1.Reference `json:"byolIdRef,omitempty" tf:"-"`

	// Selector for a Byol in ocvp to populate byolId.
	// +kubebuilder:validation:Optional
	ByolIDSelector *v1.Selector `json:"byolIdSelector,omitempty" tf:"-"`

	// (Updatable) The OCID of the compartment that contains the BYOL Allocation.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) A descriptive name for the BYOL Allocation.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`
}

type ByolAllocationObservation struct {

	// (Updatable) The quantity of licensed units that allocated to this region.
	AllocatedUnits *float64 `json:"allocatedUnits,omitempty" tf:"allocated_units,omitempty"`

	// The quantity of licensed units that not yet consumed by resources.
	AvailableUnits *float64 `json:"availableUnits,omitempty" tf:"available_units,omitempty"`

	// The OCID of the BYOL resource from which this BYOL Allocation is derived.
	ByolID *string `json:"byolId,omitempty" tf:"byol_id,omitempty"`

	// (Updatable) The OCID of the compartment that contains the BYOL Allocation.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) A descriptive name for the BYOL Allocation.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The Broadcom-supplied identifier of a BYOL license.
	EntitlementKey *string `json:"entitlementKey,omitempty" tf:"entitlement_key,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the BYOL Allocation.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The type of VMware software the BYOL applies to.  Supported values:
	SoftwareType *string `json:"softwareType,omitempty" tf:"software_type,omitempty"`

	// The current state of the BYOL Allocation.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Usage of system tag keys. These predefined keys are scoped to namespaces. Example: {orcl-cloud: {free-tier-retain: true}}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The date and time the BYOL Allocation was created, in the format defined by RFC3339. Example: 2016-08-25T21:10:29.600Z
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The date and time when the BYOL Allocation expires and becomes inactive. In the format defined byRFC3339.
	TimeTermEnd *string `json:"timeTermEnd,omitempty" tf:"time_term_end,omitempty"`

	// The date and time when the BYOL Allocation becomes active. VMware software functionality cannot begin before this time. In the format defined byRFC3339. Example: 2016-08-25T21:10:29.600Z
	TimeTermStart *string `json:"timeTermStart,omitempty" tf:"time_term_start,omitempty"`

	// The date and time the BYOL Allocation was updated, in the format defined by RFC3339.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type ByolAllocationParameters struct {

	// (Updatable) The quantity of licensed units that allocated to this region.
	// +kubebuilder:validation:Optional
	AllocatedUnits *float64 `json:"allocatedUnits,omitempty" tf:"allocated_units,omitempty"`

	// The OCID of the BYOL resource from which this BYOL Allocation is derived.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/ocvp/v1alpha1.Byol
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ByolID *string `json:"byolId,omitempty" tf:"byol_id,omitempty"`

	// Reference to a Byol in ocvp to populate byolId.
	// +kubebuilder:validation:Optional
	ByolIDRef *v1.Reference `json:"byolIdRef,omitempty" tf:"-"`

	// Selector for a Byol in ocvp to populate byolId.
	// +kubebuilder:validation:Optional
	ByolIDSelector *v1.Selector `json:"byolIdSelector,omitempty" tf:"-"`

	// (Updatable) The OCID of the compartment that contains the BYOL Allocation.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) A descriptive name for the BYOL Allocation.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`
}

// ByolAllocationSpec defines the desired state of ByolAllocation
type ByolAllocationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ByolAllocationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ByolAllocationInitParameters `json:"initProvider,omitempty"`
}

// ByolAllocationStatus defines the observed state of ByolAllocation.
type ByolAllocationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ByolAllocationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ByolAllocation is the Schema for the ByolAllocations API. Provides the Byol Allocation resource in Oracle Cloud Infrastructure Oracle Cloud VMware Solution service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type ByolAllocation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.allocatedUnits) || (has(self.initProvider) && has(self.initProvider.allocatedUnits))",message="spec.forProvider.allocatedUnits is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   ByolAllocationSpec   `json:"spec"`
	Status ByolAllocationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ByolAllocationList contains a list of ByolAllocations
type ByolAllocationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ByolAllocation `json:"items"`
}

// Repository type metadata.
var (
	ByolAllocation_Kind             = "ByolAllocation"
	ByolAllocation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ByolAllocation_Kind}.String()
	ByolAllocation_KindAPIVersion   = ByolAllocation_Kind + "." + CRDGroupVersion.String()
	ByolAllocation_GroupVersionKind = CRDGroupVersion.WithKind(ByolAllocation_Kind)
)

func init() {
	SchemeBuilder.Register(&ByolAllocation{}, &ByolAllocationList{})
}
