//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalDetailsInitParameters) DeepCopyInto(out *AdditionalDetailsInitParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalDetailsInitParameters.
func (in *AdditionalDetailsInitParameters) DeepCopy() *AdditionalDetailsInitParameters {
	if in == nil {
		return nil
	}
	out := new(AdditionalDetailsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalDetailsObservation) DeepCopyInto(out *AdditionalDetailsObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalDetailsObservation.
func (in *AdditionalDetailsObservation) DeepCopy() *AdditionalDetailsObservation {
	if in == nil {
		return nil
	}
	out := new(AdditionalDetailsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalDetailsParameters) DeepCopyInto(out *AdditionalDetailsParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalDetailsParameters.
func (in *AdditionalDetailsParameters) DeepCopy() *AdditionalDetailsParameters {
	if in == nil {
		return nil
	}
	out := new(AdditionalDetailsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingDetailsInitParameters) DeepCopyInto(out *BillingDetailsInitParameters) {
	*out = *in
	if in.HasGovSku != nil {
		in, out := &in.HasGovSku, &out.HasGovSku
		*out = new(bool)
		**out = **in
	}
	if in.Meters != nil {
		in, out := &in.Meters, &out.Meters
		*out = make([]MetersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MetricType != nil {
		in, out := &in.MetricType, &out.MetricType
		*out = new(string)
		**out = **in
	}
	if in.RateAllocation != nil {
		in, out := &in.RateAllocation, &out.RateAllocation
		*out = new(float64)
		**out = **in
	}
	if in.Sku != nil {
		in, out := &in.Sku, &out.Sku
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingDetailsInitParameters.
func (in *BillingDetailsInitParameters) DeepCopy() *BillingDetailsInitParameters {
	if in == nil {
		return nil
	}
	out := new(BillingDetailsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingDetailsObservation) DeepCopyInto(out *BillingDetailsObservation) {
	*out = *in
	if in.HasGovSku != nil {
		in, out := &in.HasGovSku, &out.HasGovSku
		*out = new(bool)
		**out = **in
	}
	if in.Meters != nil {
		in, out := &in.Meters, &out.Meters
		*out = make([]MetersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MetricType != nil {
		in, out := &in.MetricType, &out.MetricType
		*out = new(string)
		**out = **in
	}
	if in.RateAllocation != nil {
		in, out := &in.RateAllocation, &out.RateAllocation
		*out = new(float64)
		**out = **in
	}
	if in.Sku != nil {
		in, out := &in.Sku, &out.Sku
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingDetailsObservation.
func (in *BillingDetailsObservation) DeepCopy() *BillingDetailsObservation {
	if in == nil {
		return nil
	}
	out := new(BillingDetailsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingDetailsParameters) DeepCopyInto(out *BillingDetailsParameters) {
	*out = *in
	if in.HasGovSku != nil {
		in, out := &in.HasGovSku, &out.HasGovSku
		*out = new(bool)
		**out = **in
	}
	if in.Meters != nil {
		in, out := &in.Meters, &out.Meters
		*out = make([]MetersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MetricType != nil {
		in, out := &in.MetricType, &out.MetricType
		*out = new(string)
		**out = **in
	}
	if in.RateAllocation != nil {
		in, out := &in.RateAllocation, &out.RateAllocation
		*out = new(float64)
		**out = **in
	}
	if in.Sku != nil {
		in, out := &in.Sku, &out.Sku
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingDetailsParameters.
func (in *BillingDetailsParameters) DeepCopy() *BillingDetailsParameters {
	if in == nil {
		return nil
	}
	out := new(BillingDetailsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtendedMetadataInitParameters) DeepCopyInto(out *ExtendedMetadataInitParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtendedMetadataInitParameters.
func (in *ExtendedMetadataInitParameters) DeepCopy() *ExtendedMetadataInitParameters {
	if in == nil {
		return nil
	}
	out := new(ExtendedMetadataInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtendedMetadataObservation) DeepCopyInto(out *ExtendedMetadataObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtendedMetadataObservation.
func (in *ExtendedMetadataObservation) DeepCopy() *ExtendedMetadataObservation {
	if in == nil {
		return nil
	}
	out := new(ExtendedMetadataObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtendedMetadataParameters) DeepCopyInto(out *ExtendedMetadataParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtendedMetadataParameters.
func (in *ExtendedMetadataParameters) DeepCopy() *ExtendedMetadataParameters {
	if in == nil {
		return nil
	}
	out := new(ExtendedMetadataParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetersInitParameters) DeepCopyInto(out *MetersInitParameters) {
	*out = *in
	if in.ExtendedMetadata != nil {
		in, out := &in.ExtendedMetadata, &out.ExtendedMetadata
		*out = make([]ExtendedMetadataInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RateAllocation != nil {
		in, out := &in.RateAllocation, &out.RateAllocation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetersInitParameters.
func (in *MetersInitParameters) DeepCopy() *MetersInitParameters {
	if in == nil {
		return nil
	}
	out := new(MetersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetersObservation) DeepCopyInto(out *MetersObservation) {
	*out = *in
	if in.ExtendedMetadata != nil {
		in, out := &in.ExtendedMetadata, &out.ExtendedMetadata
		*out = make([]ExtendedMetadataObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RateAllocation != nil {
		in, out := &in.RateAllocation, &out.RateAllocation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetersObservation.
func (in *MetersObservation) DeepCopy() *MetersObservation {
	if in == nil {
		return nil
	}
	out := new(MetersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetersParameters) DeepCopyInto(out *MetersParameters) {
	*out = *in
	if in.ExtendedMetadata != nil {
		in, out := &in.ExtendedMetadata, &out.ExtendedMetadata
		*out = make([]ExtendedMetadataParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RateAllocation != nil {
		in, out := &in.RateAllocation, &out.RateAllocation
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetersParameters.
func (in *MetersParameters) DeepCopy() *MetersParameters {
	if in == nil {
		return nil
	}
	out := new(MetersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PricingPlanInitParameters) DeepCopyInto(out *PricingPlanInitParameters) {
	*out = *in
	if in.BillingFrequency != nil {
		in, out := &in.BillingFrequency, &out.BillingFrequency
		*out = new(string)
		**out = **in
	}
	if in.PlanDescription != nil {
		in, out := &in.PlanDescription, &out.PlanDescription
		*out = new(string)
		**out = **in
	}
	if in.PlanDuration != nil {
		in, out := &in.PlanDuration, &out.PlanDuration
		*out = new(string)
		**out = **in
	}
	if in.PlanName != nil {
		in, out := &in.PlanName, &out.PlanName
		*out = new(string)
		**out = **in
	}
	if in.PlanType != nil {
		in, out := &in.PlanType, &out.PlanType
		*out = new(string)
		**out = **in
	}
	if in.Rates != nil {
		in, out := &in.Rates, &out.Rates
		*out = make([]RatesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PricingPlanInitParameters.
func (in *PricingPlanInitParameters) DeepCopy() *PricingPlanInitParameters {
	if in == nil {
		return nil
	}
	out := new(PricingPlanInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PricingPlanObservation) DeepCopyInto(out *PricingPlanObservation) {
	*out = *in
	if in.BillingFrequency != nil {
		in, out := &in.BillingFrequency, &out.BillingFrequency
		*out = new(string)
		**out = **in
	}
	if in.PlanDescription != nil {
		in, out := &in.PlanDescription, &out.PlanDescription
		*out = new(string)
		**out = **in
	}
	if in.PlanDuration != nil {
		in, out := &in.PlanDuration, &out.PlanDuration
		*out = new(string)
		**out = **in
	}
	if in.PlanName != nil {
		in, out := &in.PlanName, &out.PlanName
		*out = new(string)
		**out = **in
	}
	if in.PlanType != nil {
		in, out := &in.PlanType, &out.PlanType
		*out = new(string)
		**out = **in
	}
	if in.Rates != nil {
		in, out := &in.Rates, &out.Rates
		*out = make([]RatesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PricingPlanObservation.
func (in *PricingPlanObservation) DeepCopy() *PricingPlanObservation {
	if in == nil {
		return nil
	}
	out := new(PricingPlanObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PricingPlanParameters) DeepCopyInto(out *PricingPlanParameters) {
	*out = *in
	if in.BillingFrequency != nil {
		in, out := &in.BillingFrequency, &out.BillingFrequency
		*out = new(string)
		**out = **in
	}
	if in.PlanDescription != nil {
		in, out := &in.PlanDescription, &out.PlanDescription
		*out = new(string)
		**out = **in
	}
	if in.PlanDuration != nil {
		in, out := &in.PlanDuration, &out.PlanDuration
		*out = new(string)
		**out = **in
	}
	if in.PlanName != nil {
		in, out := &in.PlanName, &out.PlanName
		*out = new(string)
		**out = **in
	}
	if in.PlanType != nil {
		in, out := &in.PlanType, &out.PlanType
		*out = new(string)
		**out = **in
	}
	if in.Rates != nil {
		in, out := &in.Rates, &out.Rates
		*out = make([]RatesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PricingPlanParameters.
func (in *PricingPlanParameters) DeepCopy() *PricingPlanParameters {
	if in == nil {
		return nil
	}
	out := new(PricingPlanParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RatesInitParameters) DeepCopyInto(out *RatesInitParameters) {
	*out = *in
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.Rate != nil {
		in, out := &in.Rate, &out.Rate
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RatesInitParameters.
func (in *RatesInitParameters) DeepCopy() *RatesInitParameters {
	if in == nil {
		return nil
	}
	out := new(RatesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RatesObservation) DeepCopyInto(out *RatesObservation) {
	*out = *in
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.Rate != nil {
		in, out := &in.Rate, &out.Rate
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RatesObservation.
func (in *RatesObservation) DeepCopy() *RatesObservation {
	if in == nil {
		return nil
	}
	out := new(RatesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RatesParameters) DeepCopyInto(out *RatesParameters) {
	*out = *in
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.Rate != nil {
		in, out := &in.Rate, &out.Rate
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RatesParameters.
func (in *RatesParameters) DeepCopy() *RatesParameters {
	if in == nil {
		return nil
	}
	out := new(RatesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subscription) DeepCopyInto(out *Subscription) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subscription.
func (in *Subscription) DeepCopy() *Subscription {
	if in == nil {
		return nil
	}
	out := new(Subscription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Subscription) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionDetailsInitParameters) DeepCopyInto(out *SubscriptionDetailsInitParameters) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.BillingDetails != nil {
		in, out := &in.BillingDetails, &out.BillingDetails
		*out = make([]BillingDetailsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.IsAutoRenew != nil {
		in, out := &in.IsAutoRenew, &out.IsAutoRenew
		*out = new(bool)
		**out = **in
	}
	if in.PartnerRegistrationURL != nil {
		in, out := &in.PartnerRegistrationURL, &out.PartnerRegistrationURL
		*out = new(string)
		**out = **in
	}
	if in.PricingPlan != nil {
		in, out := &in.PricingPlan, &out.PricingPlan
		*out = make([]PricingPlanInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionDetailsInitParameters.
func (in *SubscriptionDetailsInitParameters) DeepCopy() *SubscriptionDetailsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SubscriptionDetailsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionDetailsObservation) DeepCopyInto(out *SubscriptionDetailsObservation) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.BillingDetails != nil {
		in, out := &in.BillingDetails, &out.BillingDetails
		*out = make([]BillingDetailsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.IsAutoRenew != nil {
		in, out := &in.IsAutoRenew, &out.IsAutoRenew
		*out = new(bool)
		**out = **in
	}
	if in.PartnerRegistrationURL != nil {
		in, out := &in.PartnerRegistrationURL, &out.PartnerRegistrationURL
		*out = new(string)
		**out = **in
	}
	if in.PricingPlan != nil {
		in, out := &in.PricingPlan, &out.PricingPlan
		*out = make([]PricingPlanObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionDetailsObservation.
func (in *SubscriptionDetailsObservation) DeepCopy() *SubscriptionDetailsObservation {
	if in == nil {
		return nil
	}
	out := new(SubscriptionDetailsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionDetailsParameters) DeepCopyInto(out *SubscriptionDetailsParameters) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.BillingDetails != nil {
		in, out := &in.BillingDetails, &out.BillingDetails
		*out = make([]BillingDetailsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.IsAutoRenew != nil {
		in, out := &in.IsAutoRenew, &out.IsAutoRenew
		*out = new(bool)
		**out = **in
	}
	if in.PartnerRegistrationURL != nil {
		in, out := &in.PartnerRegistrationURL, &out.PartnerRegistrationURL
		*out = new(string)
		**out = **in
	}
	if in.PricingPlan != nil {
		in, out := &in.PricingPlan, &out.PricingPlan
		*out = make([]PricingPlanParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionDetailsParameters.
func (in *SubscriptionDetailsParameters) DeepCopy() *SubscriptionDetailsParameters {
	if in == nil {
		return nil
	}
	out := new(SubscriptionDetailsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionInitParameters) DeepCopyInto(out *SubscriptionInitParameters) {
	*out = *in
	if in.AdditionalDetails != nil {
		in, out := &in.AdditionalDetails, &out.AdditionalDetails
		*out = make([]AdditionalDetailsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.CompartmentIDRef != nil {
		in, out := &in.CompartmentIDRef, &out.CompartmentIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.CompartmentIDSelector != nil {
		in, out := &in.CompartmentIDSelector, &out.CompartmentIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ProductID != nil {
		in, out := &in.ProductID, &out.ProductID
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.SellerID != nil {
		in, out := &in.SellerID, &out.SellerID
		*out = new(string)
		**out = **in
	}
	if in.SourceType != nil {
		in, out := &in.SourceType, &out.SourceType
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionDetails != nil {
		in, out := &in.SubscriptionDetails, &out.SubscriptionDetails
		*out = make([]SubscriptionDetailsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TenantID != nil {
		in, out := &in.TenantID, &out.TenantID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionInitParameters.
func (in *SubscriptionInitParameters) DeepCopy() *SubscriptionInitParameters {
	if in == nil {
		return nil
	}
	out := new(SubscriptionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionList) DeepCopyInto(out *SubscriptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Subscription, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionList.
func (in *SubscriptionList) DeepCopy() *SubscriptionList {
	if in == nil {
		return nil
	}
	out := new(SubscriptionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubscriptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionObservation) DeepCopyInto(out *SubscriptionObservation) {
	*out = *in
	if in.AdditionalDetails != nil {
		in, out := &in.AdditionalDetails, &out.AdditionalDetails
		*out = make([]AdditionalDetailsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LifecycleDetails != nil {
		in, out := &in.LifecycleDetails, &out.LifecycleDetails
		*out = new(string)
		**out = **in
	}
	if in.ProductID != nil {
		in, out := &in.ProductID, &out.ProductID
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.SellerID != nil {
		in, out := &in.SellerID, &out.SellerID
		*out = new(string)
		**out = **in
	}
	if in.SourceType != nil {
		in, out := &in.SourceType, &out.SourceType
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionDetails != nil {
		in, out := &in.SubscriptionDetails, &out.SubscriptionDetails
		*out = make([]SubscriptionDetailsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TenantID != nil {
		in, out := &in.TenantID, &out.TenantID
		*out = new(string)
		**out = **in
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.TimeEnded != nil {
		in, out := &in.TimeEnded, &out.TimeEnded
		*out = new(string)
		**out = **in
	}
	if in.TimeStarted != nil {
		in, out := &in.TimeStarted, &out.TimeStarted
		*out = new(string)
		**out = **in
	}
	if in.TimeUpdated != nil {
		in, out := &in.TimeUpdated, &out.TimeUpdated
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionObservation.
func (in *SubscriptionObservation) DeepCopy() *SubscriptionObservation {
	if in == nil {
		return nil
	}
	out := new(SubscriptionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionParameters) DeepCopyInto(out *SubscriptionParameters) {
	*out = *in
	if in.AdditionalDetails != nil {
		in, out := &in.AdditionalDetails, &out.AdditionalDetails
		*out = make([]AdditionalDetailsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.CompartmentIDRef != nil {
		in, out := &in.CompartmentIDRef, &out.CompartmentIDRef
		*out = new(v1.NamespacedReference)
		(*in).DeepCopyInto(*out)
	}
	if in.CompartmentIDSelector != nil {
		in, out := &in.CompartmentIDSelector, &out.CompartmentIDSelector
		*out = new(v1.NamespacedSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ProductID != nil {
		in, out := &in.ProductID, &out.ProductID
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.SellerID != nil {
		in, out := &in.SellerID, &out.SellerID
		*out = new(string)
		**out = **in
	}
	if in.SourceType != nil {
		in, out := &in.SourceType, &out.SourceType
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionDetails != nil {
		in, out := &in.SubscriptionDetails, &out.SubscriptionDetails
		*out = make([]SubscriptionDetailsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TenantID != nil {
		in, out := &in.TenantID, &out.TenantID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionParameters.
func (in *SubscriptionParameters) DeepCopy() *SubscriptionParameters {
	if in == nil {
		return nil
	}
	out := new(SubscriptionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionSpec) DeepCopyInto(out *SubscriptionSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionSpec.
func (in *SubscriptionSpec) DeepCopy() *SubscriptionSpec {
	if in == nil {
		return nil
	}
	out := new(SubscriptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionStatus) DeepCopyInto(out *SubscriptionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionStatus.
func (in *SubscriptionStatus) DeepCopy() *SubscriptionStatus {
	if in == nil {
		return nil
	}
	out := new(SubscriptionStatus)
	in.DeepCopyInto(out)
	return out
}
