//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImport) DeepCopyInto(out *ManagementDashboardsImport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImport.
func (in *ManagementDashboardsImport) DeepCopy() *ManagementDashboardsImport {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementDashboardsImport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImportInitParameters) DeepCopyInto(out *ManagementDashboardsImportInitParameters) {
	*out = *in
	if in.ImportDetails != nil {
		in, out := &in.ImportDetails, &out.ImportDetails
		*out = new(string)
		**out = **in
	}
	if in.ImportDetailsFile != nil {
		in, out := &in.ImportDetailsFile, &out.ImportDetailsFile
		*out = new(string)
		**out = **in
	}
	if in.OverrideDashboardCompartmentOcid != nil {
		in, out := &in.OverrideDashboardCompartmentOcid, &out.OverrideDashboardCompartmentOcid
		*out = new(string)
		**out = **in
	}
	if in.OverrideSameName != nil {
		in, out := &in.OverrideSameName, &out.OverrideSameName
		*out = new(string)
		**out = **in
	}
	if in.OverrideSavedSearchCompartmentOcid != nil {
		in, out := &in.OverrideSavedSearchCompartmentOcid, &out.OverrideSavedSearchCompartmentOcid
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImportInitParameters.
func (in *ManagementDashboardsImportInitParameters) DeepCopy() *ManagementDashboardsImportInitParameters {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImportInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImportList) DeepCopyInto(out *ManagementDashboardsImportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagementDashboardsImport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImportList.
func (in *ManagementDashboardsImportList) DeepCopy() *ManagementDashboardsImportList {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementDashboardsImportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImportObservation) DeepCopyInto(out *ManagementDashboardsImportObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ImportDetails != nil {
		in, out := &in.ImportDetails, &out.ImportDetails
		*out = new(string)
		**out = **in
	}
	if in.ImportDetailsFile != nil {
		in, out := &in.ImportDetailsFile, &out.ImportDetailsFile
		*out = new(string)
		**out = **in
	}
	if in.OverrideDashboardCompartmentOcid != nil {
		in, out := &in.OverrideDashboardCompartmentOcid, &out.OverrideDashboardCompartmentOcid
		*out = new(string)
		**out = **in
	}
	if in.OverrideSameName != nil {
		in, out := &in.OverrideSameName, &out.OverrideSameName
		*out = new(string)
		**out = **in
	}
	if in.OverrideSavedSearchCompartmentOcid != nil {
		in, out := &in.OverrideSavedSearchCompartmentOcid, &out.OverrideSavedSearchCompartmentOcid
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImportObservation.
func (in *ManagementDashboardsImportObservation) DeepCopy() *ManagementDashboardsImportObservation {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImportObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImportParameters) DeepCopyInto(out *ManagementDashboardsImportParameters) {
	*out = *in
	if in.ImportDetails != nil {
		in, out := &in.ImportDetails, &out.ImportDetails
		*out = new(string)
		**out = **in
	}
	if in.ImportDetailsFile != nil {
		in, out := &in.ImportDetailsFile, &out.ImportDetailsFile
		*out = new(string)
		**out = **in
	}
	if in.OverrideDashboardCompartmentOcid != nil {
		in, out := &in.OverrideDashboardCompartmentOcid, &out.OverrideDashboardCompartmentOcid
		*out = new(string)
		**out = **in
	}
	if in.OverrideSameName != nil {
		in, out := &in.OverrideSameName, &out.OverrideSameName
		*out = new(string)
		**out = **in
	}
	if in.OverrideSavedSearchCompartmentOcid != nil {
		in, out := &in.OverrideSavedSearchCompartmentOcid, &out.OverrideSavedSearchCompartmentOcid
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImportParameters.
func (in *ManagementDashboardsImportParameters) DeepCopy() *ManagementDashboardsImportParameters {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImportParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImportSpec) DeepCopyInto(out *ManagementDashboardsImportSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImportSpec.
func (in *ManagementDashboardsImportSpec) DeepCopy() *ManagementDashboardsImportSpec {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementDashboardsImportStatus) DeepCopyInto(out *ManagementDashboardsImportStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementDashboardsImportStatus.
func (in *ManagementDashboardsImportStatus) DeepCopy() *ManagementDashboardsImportStatus {
	if in == nil {
		return nil
	}
	out := new(ManagementDashboardsImportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementSavedSearch) DeepCopyInto(out *ManagementSavedSearch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementSavedSearch.
func (in *ManagementSavedSearch) DeepCopy() *ManagementSavedSearch {
	if in == nil {
		return nil
	}
	out := new(ManagementSavedSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementSavedSearch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementSavedSearchInitParameters) DeepCopyInto(out *ManagementSavedSearchInitParameters) {
	*out = *in
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.CompartmentIDRef != nil {
		in, out := &in.CompartmentIDRef, &out.CompartmentIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.CompartmentIDSelector != nil {
		in, out := &in.CompartmentIDSelector, &out.CompartmentIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.DataConfig != nil {
		in, out := &in.DataConfig, &out.DataConfig
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DrilldownConfig != nil {
		in, out := &in.DrilldownConfig, &out.DrilldownConfig
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IsOobSavedSearch != nil {
		in, out := &in.IsOobSavedSearch, &out.IsOobSavedSearch
		*out = new(bool)
		**out = **in
	}
	if in.MetadataVersion != nil {
		in, out := &in.MetadataVersion, &out.MetadataVersion
		*out = new(string)
		**out = **in
	}
	if in.Nls != nil {
		in, out := &in.Nls, &out.Nls
		*out = new(string)
		**out = **in
	}
	if in.ParametersConfig != nil {
		in, out := &in.ParametersConfig, &out.ParametersConfig
		*out = new(string)
		**out = **in
	}
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.ProviderName != nil {
		in, out := &in.ProviderName, &out.ProviderName
		*out = new(string)
		**out = **in
	}
	if in.ProviderVersion != nil {
		in, out := &in.ProviderVersion, &out.ProviderVersion
		*out = new(string)
		**out = **in
	}
	if in.ScreenImage != nil {
		in, out := &in.ScreenImage, &out.ScreenImage
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UIConfig != nil {
		in, out := &in.UIConfig, &out.UIConfig
		*out = new(string)
		**out = **in
	}
	if in.WidgetTemplate != nil {
		in, out := &in.WidgetTemplate, &out.WidgetTemplate
		*out = new(string)
		**out = **in
	}
	if in.WidgetVM != nil {
		in, out := &in.WidgetVM, &out.WidgetVM
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementSavedSearchInitParameters.
func (in *ManagementSavedSearchInitParameters) DeepCopy() *ManagementSavedSearchInitParameters {
	if in == nil {
		return nil
	}
	out := new(ManagementSavedSearchInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementSavedSearchList) DeepCopyInto(out *ManagementSavedSearchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagementSavedSearch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementSavedSearchList.
func (in *ManagementSavedSearchList) DeepCopy() *ManagementSavedSearchList {
	if in == nil {
		return nil
	}
	out := new(ManagementSavedSearchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagementSavedSearchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementSavedSearchObservation) DeepCopyInto(out *ManagementSavedSearchObservation) {
	*out = *in
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.CreatedBy != nil {
		in, out := &in.CreatedBy, &out.CreatedBy
		*out = new(string)
		**out = **in
	}
	if in.DataConfig != nil {
		in, out := &in.DataConfig, &out.DataConfig
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DrilldownConfig != nil {
		in, out := &in.DrilldownConfig, &out.DrilldownConfig
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsOobSavedSearch != nil {
		in, out := &in.IsOobSavedSearch, &out.IsOobSavedSearch
		*out = new(bool)
		**out = **in
	}
	if in.MetadataVersion != nil {
		in, out := &in.MetadataVersion, &out.MetadataVersion
		*out = new(string)
		**out = **in
	}
	if in.Nls != nil {
		in, out := &in.Nls, &out.Nls
		*out = new(string)
		**out = **in
	}
	if in.ParametersConfig != nil {
		in, out := &in.ParametersConfig, &out.ParametersConfig
		*out = new(string)
		**out = **in
	}
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.ProviderName != nil {
		in, out := &in.ProviderName, &out.ProviderName
		*out = new(string)
		**out = **in
	}
	if in.ProviderVersion != nil {
		in, out := &in.ProviderVersion, &out.ProviderVersion
		*out = new(string)
		**out = **in
	}
	if in.ScreenImage != nil {
		in, out := &in.ScreenImage, &out.ScreenImage
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.TimeUpdated != nil {
		in, out := &in.TimeUpdated, &out.TimeUpdated
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UIConfig != nil {
		in, out := &in.UIConfig, &out.UIConfig
		*out = new(string)
		**out = **in
	}
	if in.UpdatedBy != nil {
		in, out := &in.UpdatedBy, &out.UpdatedBy
		*out = new(string)
		**out = **in
	}
	if in.WidgetTemplate != nil {
		in, out := &in.WidgetTemplate, &out.WidgetTemplate
		*out = new(string)
		**out = **in
	}
	if in.WidgetVM != nil {
		in, out := &in.WidgetVM, &out.WidgetVM
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementSavedSearchObservation.
func (in *ManagementSavedSearchObservation) DeepCopy() *ManagementSavedSearchObservation {
	if in == nil {
		return nil
	}
	out := new(ManagementSavedSearchObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementSavedSearchParameters) DeepCopyInto(out *ManagementSavedSearchParameters) {
	*out = *in
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.CompartmentIDRef != nil {
		in, out := &in.CompartmentIDRef, &out.CompartmentIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.CompartmentIDSelector != nil {
		in, out := &in.CompartmentIDSelector, &out.CompartmentIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.DataConfig != nil {
		in, out := &in.DataConfig, &out.DataConfig
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DrilldownConfig != nil {
		in, out := &in.DrilldownConfig, &out.DrilldownConfig
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IsOobSavedSearch != nil {
		in, out := &in.IsOobSavedSearch, &out.IsOobSavedSearch
		*out = new(bool)
		**out = **in
	}
	if in.MetadataVersion != nil {
		in, out := &in.MetadataVersion, &out.MetadataVersion
		*out = new(string)
		**out = **in
	}
	if in.Nls != nil {
		in, out := &in.Nls, &out.Nls
		*out = new(string)
		**out = **in
	}
	if in.ParametersConfig != nil {
		in, out := &in.ParametersConfig, &out.ParametersConfig
		*out = new(string)
		**out = **in
	}
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	if in.ProviderName != nil {
		in, out := &in.ProviderName, &out.ProviderName
		*out = new(string)
		**out = **in
	}
	if in.ProviderVersion != nil {
		in, out := &in.ProviderVersion, &out.ProviderVersion
		*out = new(string)
		**out = **in
	}
	if in.ScreenImage != nil {
		in, out := &in.ScreenImage, &out.ScreenImage
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UIConfig != nil {
		in, out := &in.UIConfig, &out.UIConfig
		*out = new(string)
		**out = **in
	}
	if in.WidgetTemplate != nil {
		in, out := &in.WidgetTemplate, &out.WidgetTemplate
		*out = new(string)
		**out = **in
	}
	if in.WidgetVM != nil {
		in, out := &in.WidgetVM, &out.WidgetVM
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementSavedSearchParameters.
func (in *ManagementSavedSearchParameters) DeepCopy() *ManagementSavedSearchParameters {
	if in == nil {
		return nil
	}
	out := new(ManagementSavedSearchParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementSavedSearchSpec) DeepCopyInto(out *ManagementSavedSearchSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementSavedSearchSpec.
func (in *ManagementSavedSearchSpec) DeepCopy() *ManagementSavedSearchSpec {
	if in == nil {
		return nil
	}
	out := new(ManagementSavedSearchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementSavedSearchStatus) DeepCopyInto(out *ManagementSavedSearchStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementSavedSearchStatus.
func (in *ManagementSavedSearchStatus) DeepCopy() *ManagementSavedSearchStatus {
	if in == nil {
		return nil
	}
	out := new(ManagementSavedSearchStatus)
	in.DeepCopyInto(out)
	return out
}
