/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ManagementSavedSearchInitParameters struct {

	// (Updatable) OCID of the compartment in which the saved search resides.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) It defines how data is fetched. A functional saved search needs a valid dataConfig. See examples on how it can be constructed for various data sources.
	DataConfig *string `json:"dataConfig,omitempty" tf:"data_config,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	DefinedTags map[string]string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Description of the saved search.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) Display name of the saved search.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Drill-down configuration to define the destination of a drill-down action.
	DrilldownConfig *string `json:"drilldownConfig,omitempty" tf:"drilldown_config,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Determines whether the saved search is an Out-of-the-Box (OOB) saved search. Note that OOB saved searches are only provided by Oracle and cannot be modified.
	IsOobSavedSearch *bool `json:"isOobSavedSearch,omitempty" tf:"is_oob_saved_search,omitempty"`

	// (Updatable) The version of the metadata defined in the API. This is maintained and enforced by dashboard server. Currently it is 2.0.
	MetadataVersion *string `json:"metadataVersion,omitempty" tf:"metadata_version,omitempty"`

	// (Updatable) JSON that contains internationalization options.
	Nls *string `json:"nls,omitempty" tf:"nls,omitempty"`

	// (Updatable) Defines parameters for the saved search.
	ParametersConfig *string `json:"parametersConfig,omitempty" tf:"parameters_config,omitempty"`

	// (Updatable) ID of the service (for example log-analytics) that owns the saved search. Each service has a unique ID.
	ProviderID *string `json:"providerId,omitempty" tf:"provider_id,omitempty"`

	// (Updatable) The user friendly name of the service (for example, Logging Analytics) that owns the saved search.
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`

	// (Updatable) The version of the metadata of the provider. This is useful for provider to version its features and metadata. Any newly created saved search (or dashboard) should use providerVersion 3.0.0.
	ProviderVersion *string `json:"providerVersion,omitempty" tf:"provider_version,omitempty"`

	// (Updatable) Screen image of the saved search.
	ScreenImage *string `json:"screenImage,omitempty" tf:"screen_image,omitempty"`

	// (Updatable) Determines how the saved search is displayed in a dashboard.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) It defines the visualization type of the widget saved search, the UI options of that visualization type, the binding of data to the visualization.
	UIConfig *string `json:"uiConfig,omitempty" tf:"ui_config,omitempty"`

	// (Updatable) The UI template that the saved search uses to render itself.
	WidgetTemplate *string `json:"widgetTemplate,omitempty" tf:"widget_template,omitempty"`

	// (Updatable) The View Model that the saved search uses to render itself.
	WidgetVM *string `json:"widgetVm,omitempty" tf:"widget_vm,omitempty"`
}

type ManagementSavedSearchObservation struct {

	// (Updatable) OCID of the compartment in which the saved search resides.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// The principal id of the user that created this saved search. This is automatically managed by the system. In Oracle Cloud Infrastructure the value is ignored. In EM it can skipped or otherwise it is ignored in both create and update API and system automatically sets its value.
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// (Updatable) It defines how data is fetched. A functional saved search needs a valid dataConfig. See examples on how it can be constructed for various data sources.
	DataConfig *string `json:"dataConfig,omitempty" tf:"data_config,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	DefinedTags map[string]string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Description of the saved search.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) Display name of the saved search.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Drill-down configuration to define the destination of a drill-down action.
	DrilldownConfig *string `json:"drilldownConfig,omitempty" tf:"drilldown_config,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// ID of the saved search, which must only be provided for Out-of-the-Box (OOB) saved search.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) Determines whether the saved search is an Out-of-the-Box (OOB) saved search. Note that OOB saved searches are only provided by Oracle and cannot be modified.
	IsOobSavedSearch *bool `json:"isOobSavedSearch,omitempty" tf:"is_oob_saved_search,omitempty"`

	// (Updatable) The version of the metadata defined in the API. This is maintained and enforced by dashboard server. Currently it is 2.0.
	MetadataVersion *string `json:"metadataVersion,omitempty" tf:"metadata_version,omitempty"`

	// (Updatable) JSON that contains internationalization options.
	Nls *string `json:"nls,omitempty" tf:"nls,omitempty"`

	// (Updatable) Defines parameters for the saved search.
	ParametersConfig *string `json:"parametersConfig,omitempty" tf:"parameters_config,omitempty"`

	// (Updatable) ID of the service (for example log-analytics) that owns the saved search. Each service has a unique ID.
	ProviderID *string `json:"providerId,omitempty" tf:"provider_id,omitempty"`

	// (Updatable) The user friendly name of the service (for example, Logging Analytics) that owns the saved search.
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`

	// (Updatable) The version of the metadata of the provider. This is useful for provider to version its features and metadata. Any newly created saved search (or dashboard) should use providerVersion 3.0.0.
	ProviderVersion *string `json:"providerVersion,omitempty" tf:"provider_version,omitempty"`

	// (Updatable) Screen image of the saved search.
	ScreenImage *string `json:"screenImage,omitempty" tf:"screen_image,omitempty"`

	// Oracle Cloud Infrastructure lifecycle status. This is automatically managed by the system.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Usage of system tag keys. These predefined keys are scoped to namespaces. Example: {"orcl-cloud.free-tier-retained": "true"}
	SystemTags map[string]string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// Date and time the saved search was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// Date and time the saved search was updated.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// (Updatable) Determines how the saved search is displayed in a dashboard.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) It defines the visualization type of the widget saved search, the UI options of that visualization type, the binding of data to the visualization.
	UIConfig *string `json:"uiConfig,omitempty" tf:"ui_config,omitempty"`

	// The principle id of the user that updated this saved search.
	UpdatedBy *string `json:"updatedBy,omitempty" tf:"updated_by,omitempty"`

	// (Updatable) The UI template that the saved search uses to render itself.
	WidgetTemplate *string `json:"widgetTemplate,omitempty" tf:"widget_template,omitempty"`

	// (Updatable) The View Model that the saved search uses to render itself.
	WidgetVM *string `json:"widgetVm,omitempty" tf:"widget_vm,omitempty"`
}

type ManagementSavedSearchParameters struct {

	// (Updatable) OCID of the compartment in which the saved search resides.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) It defines how data is fetched. A functional saved search needs a valid dataConfig. See examples on how it can be constructed for various data sources.
	// +kubebuilder:validation:Optional
	DataConfig *string `json:"dataConfig,omitempty" tf:"data_config,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +kubebuilder:validation:Optional
	DefinedTags map[string]string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Description of the saved search.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) Display name of the saved search.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Drill-down configuration to define the destination of a drill-down action.
	// +kubebuilder:validation:Optional
	DrilldownConfig *string `json:"drilldownConfig,omitempty" tf:"drilldown_config,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Determines whether the saved search is an Out-of-the-Box (OOB) saved search. Note that OOB saved searches are only provided by Oracle and cannot be modified.
	// +kubebuilder:validation:Optional
	IsOobSavedSearch *bool `json:"isOobSavedSearch,omitempty" tf:"is_oob_saved_search,omitempty"`

	// (Updatable) The version of the metadata defined in the API. This is maintained and enforced by dashboard server. Currently it is 2.0.
	// +kubebuilder:validation:Optional
	MetadataVersion *string `json:"metadataVersion,omitempty" tf:"metadata_version,omitempty"`

	// (Updatable) JSON that contains internationalization options.
	// +kubebuilder:validation:Optional
	Nls *string `json:"nls,omitempty" tf:"nls,omitempty"`

	// (Updatable) Defines parameters for the saved search.
	// +kubebuilder:validation:Optional
	ParametersConfig *string `json:"parametersConfig,omitempty" tf:"parameters_config,omitempty"`

	// (Updatable) ID of the service (for example log-analytics) that owns the saved search. Each service has a unique ID.
	// +kubebuilder:validation:Optional
	ProviderID *string `json:"providerId,omitempty" tf:"provider_id,omitempty"`

	// (Updatable) The user friendly name of the service (for example, Logging Analytics) that owns the saved search.
	// +kubebuilder:validation:Optional
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`

	// (Updatable) The version of the metadata of the provider. This is useful for provider to version its features and metadata. Any newly created saved search (or dashboard) should use providerVersion 3.0.0.
	// +kubebuilder:validation:Optional
	ProviderVersion *string `json:"providerVersion,omitempty" tf:"provider_version,omitempty"`

	// (Updatable) Screen image of the saved search.
	// +kubebuilder:validation:Optional
	ScreenImage *string `json:"screenImage,omitempty" tf:"screen_image,omitempty"`

	// (Updatable) Determines how the saved search is displayed in a dashboard.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) It defines the visualization type of the widget saved search, the UI options of that visualization type, the binding of data to the visualization.
	// +kubebuilder:validation:Optional
	UIConfig *string `json:"uiConfig,omitempty" tf:"ui_config,omitempty"`

	// (Updatable) The UI template that the saved search uses to render itself.
	// +kubebuilder:validation:Optional
	WidgetTemplate *string `json:"widgetTemplate,omitempty" tf:"widget_template,omitempty"`

	// (Updatable) The View Model that the saved search uses to render itself.
	// +kubebuilder:validation:Optional
	WidgetVM *string `json:"widgetVm,omitempty" tf:"widget_vm,omitempty"`
}

// ManagementSavedSearchSpec defines the desired state of ManagementSavedSearch
type ManagementSavedSearchSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ManagementSavedSearchParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ManagementSavedSearchInitParameters `json:"initProvider,omitempty"`
}

// ManagementSavedSearchStatus defines the observed state of ManagementSavedSearch.
type ManagementSavedSearchStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ManagementSavedSearchObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ManagementSavedSearch is the Schema for the ManagementSavedSearchs API. Provides the Management Saved Search resource in Oracle Cloud Infrastructure Management Dashboard service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type ManagementSavedSearch struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dataConfig) || (has(self.initProvider) && has(self.initProvider.dataConfig))",message="spec.forProvider.dataConfig is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.drilldownConfig) || (has(self.initProvider) && has(self.initProvider.drilldownConfig))",message="spec.forProvider.drilldownConfig is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.isOobSavedSearch) || (has(self.initProvider) && has(self.initProvider.isOobSavedSearch))",message="spec.forProvider.isOobSavedSearch is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.metadataVersion) || (has(self.initProvider) && has(self.initProvider.metadataVersion))",message="spec.forProvider.metadataVersion is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nls) || (has(self.initProvider) && has(self.initProvider.nls))",message="spec.forProvider.nls is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parametersConfig) || (has(self.initProvider) && has(self.initProvider.parametersConfig))",message="spec.forProvider.parametersConfig is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.providerId) || (has(self.initProvider) && has(self.initProvider.providerId))",message="spec.forProvider.providerId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.providerName) || (has(self.initProvider) && has(self.initProvider.providerName))",message="spec.forProvider.providerName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.providerVersion) || (has(self.initProvider) && has(self.initProvider.providerVersion))",message="spec.forProvider.providerVersion is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.screenImage) || (has(self.initProvider) && has(self.initProvider.screenImage))",message="spec.forProvider.screenImage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.uiConfig) || (has(self.initProvider) && has(self.initProvider.uiConfig))",message="spec.forProvider.uiConfig is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.widgetTemplate) || (has(self.initProvider) && has(self.initProvider.widgetTemplate))",message="spec.forProvider.widgetTemplate is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.widgetVm) || (has(self.initProvider) && has(self.initProvider.widgetVm))",message="spec.forProvider.widgetVm is a required parameter"
	Spec   ManagementSavedSearchSpec   `json:"spec"`
	Status ManagementSavedSearchStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ManagementSavedSearchList contains a list of ManagementSavedSearchs
type ManagementSavedSearchList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ManagementSavedSearch `json:"items"`
}

// Repository type metadata.
var (
	ManagementSavedSearch_Kind             = "ManagementSavedSearch"
	ManagementSavedSearch_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ManagementSavedSearch_Kind}.String()
	ManagementSavedSearch_KindAPIVersion   = ManagementSavedSearch_Kind + "." + CRDGroupVersion.String()
	ManagementSavedSearch_GroupVersionKind = CRDGroupVersion.WithKind(ManagementSavedSearch_Kind)
)

func init() {
	SchemeBuilder.Register(&ManagementSavedSearch{}, &ManagementSavedSearchList{})
}
