/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type IdentityProviderInitParameters struct {

	// (Updatable) External identity provider configuration parameters. Simple key-value pair Example: { "tenant_id": "...", "application_id_uri": "...", ... }
	Configs map[string]string `json:"configs,omitempty" tf:"configs,omitempty"`

	// (Updatable) External identity type provider.  Supported values - OCI_IAM, AZURE_AD, NONE.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IdentityProviderObservation struct {

	// (Updatable) External identity provider configuration parameters. Simple key-value pair Example: { "tenant_id": "...", "application_id_uri": "...", ... }
	Configs map[string]string `json:"configs,omitempty" tf:"configs,omitempty"`

	// (Updatable) External identity type provider.  Supported values - OCI_IAM, AZURE_AD, NONE.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IdentityProviderParameters struct {

	// (Updatable) External identity provider configuration parameters. Simple key-value pair Example: { "tenant_id": "...", "application_id_uri": "...", ... }
	// +kubebuilder:validation:Optional
	Configs map[string]string `json:"configs,omitempty" tf:"configs,omitempty"`

	// (Updatable) External identity type provider.  Supported values - OCI_IAM, AZURE_AD, NONE.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type PrerequisitesCheckInitParameters struct {
}

type PrerequisitesCheckObservation struct {

	// Status indicating the outcome of the prerequisites check.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Messages describing the prerequisites check outcome. Messages can provide actionable information when the status indicates a failure.
	StatusDetails []*string `json:"statusDetails,omitempty" tf:"status_details,omitempty"`
}

type PrerequisitesCheckParameters struct {
}

type ToolsRuntimeDatabaseToolsConnectionPropertySetInitParameters struct {

	// (Applicable when key=APEX_FA_INTEGRATION) (Updatable) APEX FA Integration key-value pairs.
	AuthenticationSubstitutions map[string]string `json:"authenticationSubstitutions,omitempty" tf:"authentication_substitutions,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The status of the Autonomous Database Serverless Resource Principal (OCI$RESOURCE_PRINCIPAL)
	AutonomousDatabaseResourcePrincipalStatus *string `json:"autonomousDatabaseResourcePrincipalStatus,omitempty" tf:"autonomous_database_resource_principal_status,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The name of the credential used by APEX to manage Object Storage Buckets and Objects as well as invoke the Document Generator function.
	CredentialKey *string `json:"credentialKey,omitempty" tf:"credential_key,omitempty"`

	// The OCID of a Database Tools connection.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.ToolsDatabaseToolsConnection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DatabaseToolsConnectionID *string `json:"databaseToolsConnectionId,omitempty" tf:"database_tools_connection_id,omitempty"`

	// Reference to a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDRef *v1.NamespacedReference `json:"databaseToolsConnectionIdRef,omitempty" tf:"-"`

	// Selector for a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDSelector *v1.NamespacedSelector `json:"databaseToolsConnectionIdSelector,omitempty" tf:"-"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The OCID of the Document Generator function
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/functions/v1alpha1.Function
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	FunctionID *string `json:"functionId,omitempty" tf:"function_id,omitempty"`

	// Reference to a Function in functions to populate functionId.
	// +kubebuilder:validation:Optional
	FunctionIDRef *v1.NamespacedReference `json:"functionIdRef,omitempty" tf:"-"`

	// Selector for a Function in functions to populate functionId.
	// +kubebuilder:validation:Optional
	FunctionIDSelector *v1.NamespacedSelector `json:"functionIdSelector,omitempty" tf:"-"`

	// (Updatable) External identity type provider
	IdentityProvider []IdentityProviderInitParameters `json:"identityProvider,omitempty" tf:"identity_provider,omitempty"`

	// (Applicable when key=APEX_FA_INTEGRATION) (Updatable) Specifies whether database credentials can be used in all workspaces on the APEX instance. Supported values include: "Y", "N" and empty string.
	InstanceDbmsCredentialEnabled *string `json:"instanceDbmsCredentialEnabled,omitempty" tf:"instance_dbms_credential_enabled,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The base endpoint URL to use to invoke the Document Generator function
	InvokeEndpoint *string `json:"invokeEndpoint,omitempty" tf:"invoke_endpoint,omitempty"`

	// (Updatable) The name of the property set
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The OCID of the compartment containing the Object Storage Buckets managed by APEX
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ObjectStorageBucketCompartmentID *string `json:"objectStorageBucketCompartmentId,omitempty" tf:"object_storage_bucket_compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate objectStorageBucketCompartmentId.
	// +kubebuilder:validation:Optional
	ObjectStorageBucketCompartmentIDRef *v1.NamespacedReference `json:"objectStorageBucketCompartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate objectStorageBucketCompartmentId.
	// +kubebuilder:validation:Optional
	ObjectStorageBucketCompartmentIDSelector *v1.NamespacedSelector `json:"objectStorageBucketCompartmentIdSelector,omitempty" tf:"-"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) Object Storage Endpoint
	ObjectStorageEndpoint *string `json:"objectStorageEndpoint,omitempty" tf:"object_storage_endpoint,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The Object Storage Namespace containing the Object Storage Buckets managed by APEX
	ObjectStorageNamespace *string `json:"objectStorageNamespace,omitempty" tf:"object_storage_namespace,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The print server type
	PrintServerType *string `json:"printServerType,omitempty" tf:"print_server_type,omitempty"`

	// The name of the property set
	PropertySetKey *string `json:"propertySetKey,omitempty" tf:"property_set_key,omitempty"`
}

type ToolsRuntimeDatabaseToolsConnectionPropertySetObservation struct {

	// (Applicable when key=APEX_FA_INTEGRATION) (Updatable) APEX FA Integration key-value pairs.
	AuthenticationSubstitutions map[string]string `json:"authenticationSubstitutions,omitempty" tf:"authentication_substitutions,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The status of the Autonomous Database Serverless Resource Principal (OCI$RESOURCE_PRINCIPAL)
	AutonomousDatabaseResourcePrincipalStatus *string `json:"autonomousDatabaseResourcePrincipalStatus,omitempty" tf:"autonomous_database_resource_principal_status,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The name of the credential used by APEX to manage Object Storage Buckets and Objects as well as invoke the Document Generator function.
	CredentialKey *string `json:"credentialKey,omitempty" tf:"credential_key,omitempty"`

	// The OCID of a Database Tools connection.
	DatabaseToolsConnectionID *string `json:"databaseToolsConnectionId,omitempty" tf:"database_tools_connection_id,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The OCID of the Document Generator function
	FunctionID *string `json:"functionId,omitempty" tf:"function_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) External identity type provider
	IdentityProvider []IdentityProviderObservation `json:"identityProvider,omitempty" tf:"identity_provider,omitempty"`

	// (Applicable when key=APEX_FA_INTEGRATION) (Updatable) Specifies whether database credentials can be used in all workspaces on the APEX instance. Supported values include: "Y", "N" and empty string.
	InstanceDbmsCredentialEnabled *string `json:"instanceDbmsCredentialEnabled,omitempty" tf:"instance_dbms_credential_enabled,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The base endpoint URL to use to invoke the Document Generator function
	InvokeEndpoint *string `json:"invokeEndpoint,omitempty" tf:"invoke_endpoint,omitempty"`

	// Indicates whether the property set is mutable or not
	IsMutable *bool `json:"isMutable,omitempty" tf:"is_mutable,omitempty"`

	// (Updatable) The name of the property set
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The OCID of the compartment containing the Object Storage Buckets managed by APEX
	ObjectStorageBucketCompartmentID *string `json:"objectStorageBucketCompartmentId,omitempty" tf:"object_storage_bucket_compartment_id,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) Object Storage Endpoint
	ObjectStorageEndpoint *string `json:"objectStorageEndpoint,omitempty" tf:"object_storage_endpoint,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The Object Storage Namespace containing the Object Storage Buckets managed by APEX
	ObjectStorageNamespace *string `json:"objectStorageNamespace,omitempty" tf:"object_storage_namespace,omitempty"`

	// The results of a prerequisites check for APEX FA integration
	PrerequisitesCheck []PrerequisitesCheckObservation `json:"prerequisitesCheck,omitempty" tf:"prerequisites_check,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The print server type
	PrintServerType *string `json:"printServerType,omitempty" tf:"print_server_type,omitempty"`

	// The name of the property set
	PropertySetKey *string `json:"propertySetKey,omitempty" tf:"property_set_key,omitempty"`

	// The APEX engine schema name
	UserKey *string `json:"userKey,omitempty" tf:"user_key,omitempty"`

	// The version of APEX
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ToolsRuntimeDatabaseToolsConnectionPropertySetParameters struct {

	// (Applicable when key=APEX_FA_INTEGRATION) (Updatable) APEX FA Integration key-value pairs.
	// +kubebuilder:validation:Optional
	AuthenticationSubstitutions map[string]string `json:"authenticationSubstitutions,omitempty" tf:"authentication_substitutions,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The status of the Autonomous Database Serverless Resource Principal (OCI$RESOURCE_PRINCIPAL)
	// +kubebuilder:validation:Optional
	AutonomousDatabaseResourcePrincipalStatus *string `json:"autonomousDatabaseResourcePrincipalStatus,omitempty" tf:"autonomous_database_resource_principal_status,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The name of the credential used by APEX to manage Object Storage Buckets and Objects as well as invoke the Document Generator function.
	// +kubebuilder:validation:Optional
	CredentialKey *string `json:"credentialKey,omitempty" tf:"credential_key,omitempty"`

	// The OCID of a Database Tools connection.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.ToolsDatabaseToolsConnection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionID *string `json:"databaseToolsConnectionId,omitempty" tf:"database_tools_connection_id,omitempty"`

	// Reference to a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDRef *v1.NamespacedReference `json:"databaseToolsConnectionIdRef,omitempty" tf:"-"`

	// Selector for a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDSelector *v1.NamespacedSelector `json:"databaseToolsConnectionIdSelector,omitempty" tf:"-"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The OCID of the Document Generator function
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/functions/v1alpha1.Function
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	FunctionID *string `json:"functionId,omitempty" tf:"function_id,omitempty"`

	// Reference to a Function in functions to populate functionId.
	// +kubebuilder:validation:Optional
	FunctionIDRef *v1.NamespacedReference `json:"functionIdRef,omitempty" tf:"-"`

	// Selector for a Function in functions to populate functionId.
	// +kubebuilder:validation:Optional
	FunctionIDSelector *v1.NamespacedSelector `json:"functionIdSelector,omitempty" tf:"-"`

	// (Updatable) External identity type provider
	// +kubebuilder:validation:Optional
	IdentityProvider []IdentityProviderParameters `json:"identityProvider,omitempty" tf:"identity_provider,omitempty"`

	// (Applicable when key=APEX_FA_INTEGRATION) (Updatable) Specifies whether database credentials can be used in all workspaces on the APEX instance. Supported values include: "Y", "N" and empty string.
	// +kubebuilder:validation:Optional
	InstanceDbmsCredentialEnabled *string `json:"instanceDbmsCredentialEnabled,omitempty" tf:"instance_dbms_credential_enabled,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The base endpoint URL to use to invoke the Document Generator function
	// +kubebuilder:validation:Optional
	InvokeEndpoint *string `json:"invokeEndpoint,omitempty" tf:"invoke_endpoint,omitempty"`

	// (Updatable) The name of the property set
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The OCID of the compartment containing the Object Storage Buckets managed by APEX
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ObjectStorageBucketCompartmentID *string `json:"objectStorageBucketCompartmentId,omitempty" tf:"object_storage_bucket_compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate objectStorageBucketCompartmentId.
	// +kubebuilder:validation:Optional
	ObjectStorageBucketCompartmentIDRef *v1.NamespacedReference `json:"objectStorageBucketCompartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate objectStorageBucketCompartmentId.
	// +kubebuilder:validation:Optional
	ObjectStorageBucketCompartmentIDSelector *v1.NamespacedSelector `json:"objectStorageBucketCompartmentIdSelector,omitempty" tf:"-"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) Object Storage Endpoint
	// +kubebuilder:validation:Optional
	ObjectStorageEndpoint *string `json:"objectStorageEndpoint,omitempty" tf:"object_storage_endpoint,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The Object Storage Namespace containing the Object Storage Buckets managed by APEX
	// +kubebuilder:validation:Optional
	ObjectStorageNamespace *string `json:"objectStorageNamespace,omitempty" tf:"object_storage_namespace,omitempty"`

	// (Applicable when key=APEX_DOCUMENT_GENERATOR) (Updatable) The print server type
	// +kubebuilder:validation:Optional
	PrintServerType *string `json:"printServerType,omitempty" tf:"print_server_type,omitempty"`

	// The name of the property set
	// +kubebuilder:validation:Optional
	PropertySetKey *string `json:"propertySetKey,omitempty" tf:"property_set_key,omitempty"`
}

// ToolsRuntimeDatabaseToolsConnectionPropertySetSpec defines the desired state of ToolsRuntimeDatabaseToolsConnectionPropertySet
type ToolsRuntimeDatabaseToolsConnectionPropertySetSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ToolsRuntimeDatabaseToolsConnectionPropertySetParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ToolsRuntimeDatabaseToolsConnectionPropertySetInitParameters `json:"initProvider,omitempty"`
}

// ToolsRuntimeDatabaseToolsConnectionPropertySetStatus defines the observed state of ToolsRuntimeDatabaseToolsConnectionPropertySet.
type ToolsRuntimeDatabaseToolsConnectionPropertySetStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ToolsRuntimeDatabaseToolsConnectionPropertySetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ToolsRuntimeDatabaseToolsConnectionPropertySet is the Schema for the ToolsRuntimeDatabaseToolsConnectionPropertySets API. Provides the Database Tools Connection Property Set resource in Oracle Cloud Infrastructure Database Tools Runtime service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type ToolsRuntimeDatabaseToolsConnectionPropertySet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.propertySetKey) || (has(self.initProvider) && has(self.initProvider.propertySetKey))",message="spec.forProvider.propertySetKey is a required parameter"
	Spec   ToolsRuntimeDatabaseToolsConnectionPropertySetSpec   `json:"spec"`
	Status ToolsRuntimeDatabaseToolsConnectionPropertySetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ToolsRuntimeDatabaseToolsConnectionPropertySetList contains a list of ToolsRuntimeDatabaseToolsConnectionPropertySets
type ToolsRuntimeDatabaseToolsConnectionPropertySetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ToolsRuntimeDatabaseToolsConnectionPropertySet `json:"items"`
}

// Repository type metadata.
var (
	ToolsRuntimeDatabaseToolsConnectionPropertySet_Kind             = "ToolsRuntimeDatabaseToolsConnectionPropertySet"
	ToolsRuntimeDatabaseToolsConnectionPropertySet_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ToolsRuntimeDatabaseToolsConnectionPropertySet_Kind}.String()
	ToolsRuntimeDatabaseToolsConnectionPropertySet_KindAPIVersion   = ToolsRuntimeDatabaseToolsConnectionPropertySet_Kind + "." + CRDGroupVersion.String()
	ToolsRuntimeDatabaseToolsConnectionPropertySet_GroupVersionKind = CRDGroupVersion.WithKind(ToolsRuntimeDatabaseToolsConnectionPropertySet_Kind)
)

func init() {
	SchemeBuilder.Register(&ToolsRuntimeDatabaseToolsConnectionPropertySet{}, &ToolsRuntimeDatabaseToolsConnectionPropertySetList{})
}
