/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BucketInitParameters struct {

	// (Updatable) A Cloud Storage bucket for an MCP Server.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Updatable) The Object Storage namespace to use.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type BucketObservation struct {

	// (Updatable) A Cloud Storage bucket for an MCP Server.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Updatable) The Object Storage namespace to use.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type BucketParameters struct {

	// (Updatable) A Cloud Storage bucket for an MCP Server.
	// +kubebuilder:validation:Optional
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Updatable) The Object Storage namespace to use.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type BuiltInRolesInitParameters struct {
}

type BuiltInRolesObservation struct {

	// (Updatable) The description of the custom role.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The display name of the custom role.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type BuiltInRolesParameters struct {
}

type CustomRolesInitParameters struct {

	// (Updatable) The description of the custom role.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The display name of the custom role.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type CustomRolesObservation struct {

	// (Updatable) The description of the custom role.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The display name of the custom role.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type CustomRolesParameters struct {

	// (Updatable) The description of the custom role.
	// +kubebuilder:validation:Optional
	Description *string `json:"description" tf:"description,omitempty"`

	// (Updatable) The display name of the custom role.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName" tf:"display_name,omitempty"`
}

type StorageInitParameters struct {

	// (Updatable) A Cloud Storage bucket for an MCP Server.
	Bucket []BucketInitParameters `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Type of the lock.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type StorageObservation struct {

	// (Updatable) A Cloud Storage bucket for an MCP Server.
	Bucket []BucketObservation `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Type of the lock.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type StorageParameters struct {

	// (Updatable) A Cloud Storage bucket for an MCP Server.
	// +kubebuilder:validation:Optional
	Bucket []BucketParameters `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Type of the lock.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type ToolsDatabaseToolsMcpServerEndpointsInitParameters struct {
}

type ToolsDatabaseToolsMcpServerEndpointsObservation struct {

	// The URI endpoint of the MCP server
	Endpoint *string `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// Type of the lock.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ToolsDatabaseToolsMcpServerEndpointsParameters struct {
}

type ToolsDatabaseToolsMcpServerInitParameters struct {

	// (Updatable) Access token expiry in seconds
	AccessTokenExpiryInSeconds *int64 `json:"accessTokenExpiryInSeconds,omitempty" tf:"access_token_expiry_in_seconds,omitempty"`

	// (Updatable) The OCID of the compartment containing the Database Tools MCP server.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Custom Roles associated with the MCP Server.
	CustomRoles []CustomRolesInitParameters `json:"customRoles,omitempty" tf:"custom_roles,omitempty"`

	// The OCID of the related Database Tools connection.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.ToolsDatabaseToolsConnection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DatabaseToolsConnectionID *string `json:"databaseToolsConnectionId,omitempty" tf:"database_tools_connection_id,omitempty"`

	// Reference to a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDRef *v1.NamespacedReference `json:"databaseToolsConnectionIdRef,omitempty" tf:"-"`

	// Selector for a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDSelector *v1.NamespacedSelector `json:"databaseToolsConnectionIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	DefinedTags map[string]string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The description of the custom role.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The display name of the custom role.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The OCID of the associated identity domain.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Domain
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DomainID *string `json:"domainId,omitempty" tf:"domain_id,omitempty"`

	// Reference to a Domain in identity to populate domainId.
	// +kubebuilder:validation:Optional
	DomainIDRef *v1.NamespacedReference `json:"domainIdRef,omitempty" tf:"-"`

	// Selector for a Domain in identity to populate domainId.
	// +kubebuilder:validation:Optional
	DomainIDSelector *v1.NamespacedSelector `json:"domainIdSelector,omitempty" tf:"-"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	FreeformTags map[string]string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// Locks associated with this resource.
	Locks []ToolsDatabaseToolsMcpServerLocksInitParameters `json:"locks,omitempty" tf:"locks,omitempty"`

	// (Updatable) Refresh token expiry in seconds
	RefreshTokenExpiryInSeconds *int64 `json:"refreshTokenExpiryInSeconds,omitempty" tf:"refresh_token_expiry_in_seconds,omitempty"`

	// Specifies the identity used by the Database Tools MCP server to issue requests to other Oracle Cloud Infrastructure services (e.g., Secrets in Vault).
	RuntimeIdentity *string `json:"runtimeIdentity,omitempty" tf:"runtime_identity,omitempty"`

	// (Updatable) The storage option used when running a tool asynchronously.
	Storage []StorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// Type of the lock.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ToolsDatabaseToolsMcpServerLocksInitParameters struct {

	// A message added by the creator of the lock. This is typically used to give an indication of why the resource is locked.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// The id of the resource that is locking this resource. Indicates that deleting this resource will remove the lock.
	RelatedResourceID *string `json:"relatedResourceId,omitempty" tf:"related_resource_id,omitempty"`

	// When the lock was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// Type of the lock.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ToolsDatabaseToolsMcpServerLocksObservation struct {

	// A message added by the creator of the lock. This is typically used to give an indication of why the resource is locked.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// The id of the resource that is locking this resource. Indicates that deleting this resource will remove the lock.
	RelatedResourceID *string `json:"relatedResourceId,omitempty" tf:"related_resource_id,omitempty"`

	// When the lock was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// Type of the lock.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ToolsDatabaseToolsMcpServerLocksParameters struct {

	// A message added by the creator of the lock. This is typically used to give an indication of why the resource is locked.
	// +kubebuilder:validation:Optional
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// The id of the resource that is locking this resource. Indicates that deleting this resource will remove the lock.
	// +kubebuilder:validation:Optional
	RelatedResourceID *string `json:"relatedResourceId,omitempty" tf:"related_resource_id,omitempty"`

	// When the lock was created.
	// +kubebuilder:validation:Optional
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// Type of the lock.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type ToolsDatabaseToolsMcpServerObservation struct {

	// (Updatable) Access token expiry in seconds
	AccessTokenExpiryInSeconds *int64 `json:"accessTokenExpiryInSeconds,omitempty" tf:"access_token_expiry_in_seconds,omitempty"`

	// Built-in roles associated with the MCP Server.
	BuiltInRoles []BuiltInRolesObservation `json:"builtInRoles,omitempty" tf:"built_in_roles,omitempty"`

	// (Updatable) The OCID of the compartment containing the Database Tools MCP server.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Custom Roles associated with the MCP Server.
	CustomRoles []CustomRolesObservation `json:"customRoles,omitempty" tf:"custom_roles,omitempty"`

	// The OCID of the related Database Tools connection.
	DatabaseToolsConnectionID *string `json:"databaseToolsConnectionId,omitempty" tf:"database_tools_connection_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	DefinedTags map[string]string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The description of the custom role.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The display name of the custom role.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The OCID of the associated domain application (Oracle Cloud Service).
	DomainAppID *string `json:"domainAppId,omitempty" tf:"domain_app_id,omitempty"`

	// The OCID of the associated identity domain.
	DomainID *string `json:"domainId,omitempty" tf:"domain_id,omitempty"`

	// Invoke endpoints for the MCP server.
	Endpoints []ToolsDatabaseToolsMcpServerEndpointsObservation `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	FreeformTags map[string]string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the Database Tools MCP server.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A message describing the current state in more detail. For example, this message can be used to provide actionable information for a resource in the Failed state.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// Locks associated with this resource.
	Locks []ToolsDatabaseToolsMcpServerLocksObservation `json:"locks,omitempty" tf:"locks,omitempty"`

	// (Updatable) Refresh token expiry in seconds
	RefreshTokenExpiryInSeconds *int64 `json:"refreshTokenExpiryInSeconds,omitempty" tf:"refresh_token_expiry_in_seconds,omitempty"`

	// A related resource
	RelatedResource []ToolsDatabaseToolsMcpServerRelatedResourceObservation `json:"relatedResource,omitempty" tf:"related_resource,omitempty"`

	// Specifies the identity used by the Database Tools MCP server to issue requests to other Oracle Cloud Infrastructure services (e.g., Secrets in Vault).
	RuntimeIdentity *string `json:"runtimeIdentity,omitempty" tf:"runtime_identity,omitempty"`

	// The current state of the Database Tools MCP server.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (Updatable) The storage option used when running a tool asynchronously.
	Storage []StorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// Usage of system tag keys. These predefined keys are scoped to namespaces. Example: {"orcl-cloud.free-tier-retained": "true"}
	SystemTags map[string]string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// When the lock was created.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The time the Database Tools MCP server was updated. An RFC3339 formatted datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// Type of the lock.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ToolsDatabaseToolsMcpServerParameters struct {

	// (Updatable) Access token expiry in seconds
	// +kubebuilder:validation:Optional
	AccessTokenExpiryInSeconds *int64 `json:"accessTokenExpiryInSeconds,omitempty" tf:"access_token_expiry_in_seconds,omitempty"`

	// (Updatable) The OCID of the compartment containing the Database Tools MCP server.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Custom Roles associated with the MCP Server.
	// +kubebuilder:validation:Optional
	CustomRoles []CustomRolesParameters `json:"customRoles,omitempty" tf:"custom_roles,omitempty"`

	// The OCID of the related Database Tools connection.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.ToolsDatabaseToolsConnection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionID *string `json:"databaseToolsConnectionId,omitempty" tf:"database_tools_connection_id,omitempty"`

	// Reference to a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDRef *v1.NamespacedReference `json:"databaseToolsConnectionIdRef,omitempty" tf:"-"`

	// Selector for a ToolsDatabaseToolsConnection in database to populate databaseToolsConnectionId.
	// +kubebuilder:validation:Optional
	DatabaseToolsConnectionIDSelector *v1.NamespacedSelector `json:"databaseToolsConnectionIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +kubebuilder:validation:Optional
	DefinedTags map[string]string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The description of the custom role.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The display name of the custom role.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The OCID of the associated identity domain.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Domain
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DomainID *string `json:"domainId,omitempty" tf:"domain_id,omitempty"`

	// Reference to a Domain in identity to populate domainId.
	// +kubebuilder:validation:Optional
	DomainIDRef *v1.NamespacedReference `json:"domainIdRef,omitempty" tf:"-"`

	// Selector for a Domain in identity to populate domainId.
	// +kubebuilder:validation:Optional
	DomainIDSelector *v1.NamespacedSelector `json:"domainIdSelector,omitempty" tf:"-"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// Locks associated with this resource.
	// +kubebuilder:validation:Optional
	Locks []ToolsDatabaseToolsMcpServerLocksParameters `json:"locks,omitempty" tf:"locks,omitempty"`

	// (Updatable) Refresh token expiry in seconds
	// +kubebuilder:validation:Optional
	RefreshTokenExpiryInSeconds *int64 `json:"refreshTokenExpiryInSeconds,omitempty" tf:"refresh_token_expiry_in_seconds,omitempty"`

	// Specifies the identity used by the Database Tools MCP server to issue requests to other Oracle Cloud Infrastructure services (e.g., Secrets in Vault).
	// +kubebuilder:validation:Optional
	RuntimeIdentity *string `json:"runtimeIdentity,omitempty" tf:"runtime_identity,omitempty"`

	// (Updatable) The storage option used when running a tool asynchronously.
	// +kubebuilder:validation:Optional
	Storage []StorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// Type of the lock.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ToolsDatabaseToolsMcpServerRelatedResourceInitParameters struct {
}

type ToolsDatabaseToolsMcpServerRelatedResourceObservation struct {

	// The resource entity type.
	EntityType *string `json:"entityType,omitempty" tf:"entity_type,omitempty"`

	// The OCID of the related resource.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`
}

type ToolsDatabaseToolsMcpServerRelatedResourceParameters struct {
}

// ToolsDatabaseToolsMcpServerSpec defines the desired state of ToolsDatabaseToolsMcpServer
type ToolsDatabaseToolsMcpServerSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ToolsDatabaseToolsMcpServerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ToolsDatabaseToolsMcpServerInitParameters `json:"initProvider,omitempty"`
}

// ToolsDatabaseToolsMcpServerStatus defines the observed state of ToolsDatabaseToolsMcpServer.
type ToolsDatabaseToolsMcpServerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ToolsDatabaseToolsMcpServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ToolsDatabaseToolsMcpServer is the Schema for the ToolsDatabaseToolsMcpServers API. Provides the Database Tools Mcp Server resource in Oracle Cloud Infrastructure Database Tools service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type ToolsDatabaseToolsMcpServer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ToolsDatabaseToolsMcpServerSpec   `json:"spec"`
	Status ToolsDatabaseToolsMcpServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ToolsDatabaseToolsMcpServerList contains a list of ToolsDatabaseToolsMcpServers
type ToolsDatabaseToolsMcpServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ToolsDatabaseToolsMcpServer `json:"items"`
}

// Repository type metadata.
var (
	ToolsDatabaseToolsMcpServer_Kind             = "ToolsDatabaseToolsMcpServer"
	ToolsDatabaseToolsMcpServer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ToolsDatabaseToolsMcpServer_Kind}.String()
	ToolsDatabaseToolsMcpServer_KindAPIVersion   = ToolsDatabaseToolsMcpServer_Kind + "." + CRDGroupVersion.String()
	ToolsDatabaseToolsMcpServer_GroupVersionKind = CRDGroupVersion.WithKind(ToolsDatabaseToolsMcpServer_Kind)
)

func init() {
	SchemeBuilder.Register(&ToolsDatabaseToolsMcpServer{}, &ToolsDatabaseToolsMcpServerList{})
}
