/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BucketDetailsInitParameters struct {

	// Type of bucket. SENDER pipelines can be SOURCE, TRANSFER, REJECT, or FAILED. RECEIVER pipelines have a DESTINATION bucket.
	BucketType *string `json:"bucketType,omitempty" tf:"bucket_type,omitempty"`

	// OCID of the bucket.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the bucket.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Namespace of the bucket.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type BucketDetailsObservation struct {

	// Type of bucket. SENDER pipelines can be SOURCE, TRANSFER, REJECT, or FAILED. RECEIVER pipelines have a DESTINATION bucket.
	BucketType *string `json:"bucketType,omitempty" tf:"bucket_type,omitempty"`

	// OCID of the bucket.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the bucket.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Namespace of the bucket.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type BucketDetailsParameters struct {

	// Type of bucket. SENDER pipelines can be SOURCE, TRANSFER, REJECT, or FAILED. RECEIVER pipelines have a DESTINATION bucket.
	// +kubebuilder:validation:Optional
	BucketType *string `json:"bucketType" tf:"bucket_type,omitempty"`

	// OCID of the bucket.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// Name of the bucket.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Namespace of the bucket.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace" tf:"namespace,omitempty"`
}

type GdpPipelineInitParameters struct {

	// (Updatable) The KMS vault OCID used for cryptographic approvals of transfers.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/kms/v1alpha1.Vault
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ApprovalKeyVaultID *string `json:"approvalKeyVaultId,omitempty" tf:"approval_key_vault_id,omitempty"`

	// Reference to a Vault in kms to populate approvalKeyVaultId.
	// +kubebuilder:validation:Optional
	ApprovalKeyVaultIDRef *v1.NamespacedReference `json:"approvalKeyVaultIdRef,omitempty" tf:"-"`

	// Selector for a Vault in kms to populate approvalKeyVaultId.
	// +kubebuilder:validation:Optional
	ApprovalKeyVaultIDSelector *v1.NamespacedSelector `json:"approvalKeyVaultIdSelector,omitempty" tf:"-"`

	// (Updatable) Authorization information about the pipeline being configured.
	AuthorizationDetails *string `json:"authorizationDetails,omitempty" tf:"authorization_details,omitempty"`

	// Configuration information about the buckets used for this pipeline.
	BucketDetails []BucketDetailsInitParameters `json:"bucketDetails,omitempty" tf:"bucket_details,omitempty"`

	// (Updatable) The OCID of the compartment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Short field input by customer for a description of the data pipeline use-case.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) Pipeline short name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The environment where the pipeline resides. Valid values are COMMERCIAL or USGOV. Defaults to COMMERCIAL.
	Env *string `json:"env,omitempty" tf:"env,omitempty"`

	// (Updatable) List of file types allowed to be transferred in the pipeline according to the authorization details (e.g. .pdf, .xml, .doc).
	FileTypes []*string `json:"fileTypes,omitempty" tf:"file_types,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Determines whether file transfers need to go through an approval workflow.
	IsApprovalNeeded *bool `json:"isApprovalNeeded,omitempty" tf:"is_approval_needed,omitempty"`

	// (Updatable) Determines whether file must be chunked during the transfer. This is only a property of SENDER pipelines.
	IsChunkingEnabled *bool `json:"isChunkingEnabled,omitempty" tf:"is_chunking_enabled,omitempty"`

	// (Updatable) Enable file override feature in destination bucket. If 2 files with same name exist in destination bucket, original file will be overwritten.
	IsFileOverrideInDestinationEnabled *bool `json:"isFileOverrideInDestinationEnabled,omitempty" tf:"is_file_override_in_destination_enabled,omitempty"`

	// (Updatable) Determines whether GDP Scanning should be enabled for the pipeline.
	IsScanningEnabled *bool `json:"isScanningEnabled,omitempty" tf:"is_scanning_enabled,omitempty"`

	// Public region name where the peered pipeline exists.
	PeeringRegion *string `json:"peeringRegion,omitempty" tf:"peering_region,omitempty"`

	// Type of pipeline. Can be SENDER or RECEIVER.
	PipelineType *string `json:"pipelineType,omitempty" tf:"pipeline_type,omitempty"`

	// (Updatable) the OCID of the service log group.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/logging/v1alpha1.LogGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ServiceLogGroupID *string `json:"serviceLogGroupId,omitempty" tf:"service_log_group_id,omitempty"`

	// Reference to a LogGroup in logging to populate serviceLogGroupId.
	// +kubebuilder:validation:Optional
	ServiceLogGroupIDRef *v1.NamespacedReference `json:"serviceLogGroupIdRef,omitempty" tf:"-"`

	// Selector for a LogGroup in logging to populate serviceLogGroupId.
	// +kubebuilder:validation:Optional
	ServiceLogGroupIDSelector *v1.NamespacedSelector `json:"serviceLogGroupIdSelector,omitempty" tf:"-"`

	// The current state of the pipeline.
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type GdpPipelineObservation struct {

	// (Updatable) The KMS vault OCID used for cryptographic approvals of transfers.
	ApprovalKeyVaultID *string `json:"approvalKeyVaultId,omitempty" tf:"approval_key_vault_id,omitempty"`

	// (Updatable) Authorization information about the pipeline being configured.
	AuthorizationDetails *string `json:"authorizationDetails,omitempty" tf:"authorization_details,omitempty"`

	// Configuration information about the buckets used for this pipeline.
	BucketDetails []BucketDetailsObservation `json:"bucketDetails,omitempty" tf:"bucket_details,omitempty"`

	// (Updatable) The OCID of the compartment.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Short field input by customer for a description of the data pipeline use-case.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) Pipeline short name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The environment where the pipeline resides. Valid values are COMMERCIAL or USGOV. Defaults to COMMERCIAL.
	Env *string `json:"env,omitempty" tf:"env,omitempty"`

	// (Updatable) List of file types allowed to be transferred in the pipeline according to the authorization details (e.g. .pdf, .xml, .doc).
	FileTypes []*string `json:"fileTypes,omitempty" tf:"file_types,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// OCID of the bucket.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) Determines whether file transfers need to go through an approval workflow.
	IsApprovalNeeded *bool `json:"isApprovalNeeded,omitempty" tf:"is_approval_needed,omitempty"`

	// (Updatable) Determines whether file must be chunked during the transfer. This is only a property of SENDER pipelines.
	IsChunkingEnabled *bool `json:"isChunkingEnabled,omitempty" tf:"is_chunking_enabled,omitempty"`

	// (Updatable) Enable file override feature in destination bucket. If 2 files with same name exist in destination bucket, original file will be overwritten.
	IsFileOverrideInDestinationEnabled *bool `json:"isFileOverrideInDestinationEnabled,omitempty" tf:"is_file_override_in_destination_enabled,omitempty"`

	// (Updatable) Determines whether GDP Scanning should be enabled for the pipeline.
	IsScanningEnabled *bool `json:"isScanningEnabled,omitempty" tf:"is_scanning_enabled,omitempty"`

	// Additional details about the current state of the pipeline.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// OCID of the peered pipeline. This null for SENDER pipeline.
	PeeredGdpPipelineID *string `json:"peeredGdpPipelineId,omitempty" tf:"peered_gdp_pipeline_id,omitempty"`

	// Public region name where the peered pipeline exists.
	PeeringRegion *string `json:"peeringRegion,omitempty" tf:"peering_region,omitempty"`

	// Type of pipeline. Can be SENDER or RECEIVER.
	PipelineType *string `json:"pipelineType,omitempty" tf:"pipeline_type,omitempty"`

	// (Updatable) the OCID of the service log group.
	ServiceLogGroupID *string `json:"serviceLogGroupId,omitempty" tf:"service_log_group_id,omitempty"`

	// The current state of the pipeline.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace. Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The time the the pipeline was created. An RFC3339 formatted datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The time the pipeline was updated. An RFC3339 formatted datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type GdpPipelineParameters struct {

	// (Updatable) The KMS vault OCID used for cryptographic approvals of transfers.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/kms/v1alpha1.Vault
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ApprovalKeyVaultID *string `json:"approvalKeyVaultId,omitempty" tf:"approval_key_vault_id,omitempty"`

	// Reference to a Vault in kms to populate approvalKeyVaultId.
	// +kubebuilder:validation:Optional
	ApprovalKeyVaultIDRef *v1.NamespacedReference `json:"approvalKeyVaultIdRef,omitempty" tf:"-"`

	// Selector for a Vault in kms to populate approvalKeyVaultId.
	// +kubebuilder:validation:Optional
	ApprovalKeyVaultIDSelector *v1.NamespacedSelector `json:"approvalKeyVaultIdSelector,omitempty" tf:"-"`

	// (Updatable) Authorization information about the pipeline being configured.
	// +kubebuilder:validation:Optional
	AuthorizationDetails *string `json:"authorizationDetails,omitempty" tf:"authorization_details,omitempty"`

	// Configuration information about the buckets used for this pipeline.
	// +kubebuilder:validation:Optional
	BucketDetails []BucketDetailsParameters `json:"bucketDetails,omitempty" tf:"bucket_details,omitempty"`

	// (Updatable) The OCID of the compartment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Short field input by customer for a description of the data pipeline use-case.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) Pipeline short name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The environment where the pipeline resides. Valid values are COMMERCIAL or USGOV. Defaults to COMMERCIAL.
	// +kubebuilder:validation:Optional
	Env *string `json:"env,omitempty" tf:"env,omitempty"`

	// (Updatable) List of file types allowed to be transferred in the pipeline according to the authorization details (e.g. .pdf, .xml, .doc).
	// +kubebuilder:validation:Optional
	FileTypes []*string `json:"fileTypes,omitempty" tf:"file_types,omitempty"`

	// (Updatable) Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only. Example: {"bar-key": "value"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Determines whether file transfers need to go through an approval workflow.
	// +kubebuilder:validation:Optional
	IsApprovalNeeded *bool `json:"isApprovalNeeded,omitempty" tf:"is_approval_needed,omitempty"`

	// (Updatable) Determines whether file must be chunked during the transfer. This is only a property of SENDER pipelines.
	// +kubebuilder:validation:Optional
	IsChunkingEnabled *bool `json:"isChunkingEnabled,omitempty" tf:"is_chunking_enabled,omitempty"`

	// (Updatable) Enable file override feature in destination bucket. If 2 files with same name exist in destination bucket, original file will be overwritten.
	// +kubebuilder:validation:Optional
	IsFileOverrideInDestinationEnabled *bool `json:"isFileOverrideInDestinationEnabled,omitempty" tf:"is_file_override_in_destination_enabled,omitempty"`

	// (Updatable) Determines whether GDP Scanning should be enabled for the pipeline.
	// +kubebuilder:validation:Optional
	IsScanningEnabled *bool `json:"isScanningEnabled,omitempty" tf:"is_scanning_enabled,omitempty"`

	// Public region name where the peered pipeline exists.
	// +kubebuilder:validation:Optional
	PeeringRegion *string `json:"peeringRegion,omitempty" tf:"peering_region,omitempty"`

	// Type of pipeline. Can be SENDER or RECEIVER.
	// +kubebuilder:validation:Optional
	PipelineType *string `json:"pipelineType,omitempty" tf:"pipeline_type,omitempty"`

	// (Updatable) the OCID of the service log group.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/logging/v1alpha1.LogGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ServiceLogGroupID *string `json:"serviceLogGroupId,omitempty" tf:"service_log_group_id,omitempty"`

	// Reference to a LogGroup in logging to populate serviceLogGroupId.
	// +kubebuilder:validation:Optional
	ServiceLogGroupIDRef *v1.NamespacedReference `json:"serviceLogGroupIdRef,omitempty" tf:"-"`

	// Selector for a LogGroup in logging to populate serviceLogGroupId.
	// +kubebuilder:validation:Optional
	ServiceLogGroupIDSelector *v1.NamespacedSelector `json:"serviceLogGroupIdSelector,omitempty" tf:"-"`

	// The current state of the pipeline.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

// GdpPipelineSpec defines the desired state of GdpPipeline
type GdpPipelineSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GdpPipelineParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GdpPipelineInitParameters `json:"initProvider,omitempty"`
}

// GdpPipelineStatus defines the observed state of GdpPipeline.
type GdpPipelineStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GdpPipelineObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GdpPipeline is the Schema for the GdpPipelines API. Provides the Gdp Pipeline resource in Oracle Cloud Infrastructure Gdp service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type GdpPipeline struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.bucketDetails) || (has(self.initProvider) && has(self.initProvider.bucketDetails))",message="spec.forProvider.bucketDetails is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.peeringRegion) || (has(self.initProvider) && has(self.initProvider.peeringRegion))",message="spec.forProvider.peeringRegion is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.pipelineType) || (has(self.initProvider) && has(self.initProvider.pipelineType))",message="spec.forProvider.pipelineType is a required parameter"
	Spec   GdpPipelineSpec   `json:"spec"`
	Status GdpPipelineStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GdpPipelineList contains a list of GdpPipelines
type GdpPipelineList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GdpPipeline `json:"items"`
}

// Repository type metadata.
var (
	GdpPipeline_Kind             = "GdpPipeline"
	GdpPipeline_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GdpPipeline_Kind}.String()
	GdpPipeline_KindAPIVersion   = GdpPipeline_Kind + "." + CRDGroupVersion.String()
	GdpPipeline_GroupVersionKind = CRDGroupVersion.WithKind(GdpPipeline_Kind)
)

func init() {
	SchemeBuilder.Register(&GdpPipeline{}, &GdpPipelineList{})
}
