//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BucketDetailsInitParameters) DeepCopyInto(out *BucketDetailsInitParameters) {
	*out = *in
	if in.BucketType != nil {
		in, out := &in.BucketType, &out.BucketType
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BucketDetailsInitParameters.
func (in *BucketDetailsInitParameters) DeepCopy() *BucketDetailsInitParameters {
	if in == nil {
		return nil
	}
	out := new(BucketDetailsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BucketDetailsObservation) DeepCopyInto(out *BucketDetailsObservation) {
	*out = *in
	if in.BucketType != nil {
		in, out := &in.BucketType, &out.BucketType
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BucketDetailsObservation.
func (in *BucketDetailsObservation) DeepCopy() *BucketDetailsObservation {
	if in == nil {
		return nil
	}
	out := new(BucketDetailsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BucketDetailsParameters) DeepCopyInto(out *BucketDetailsParameters) {
	*out = *in
	if in.BucketType != nil {
		in, out := &in.BucketType, &out.BucketType
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BucketDetailsParameters.
func (in *BucketDetailsParameters) DeepCopy() *BucketDetailsParameters {
	if in == nil {
		return nil
	}
	out := new(BucketDetailsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GdpPipeline) DeepCopyInto(out *GdpPipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GdpPipeline.
func (in *GdpPipeline) DeepCopy() *GdpPipeline {
	if in == nil {
		return nil
	}
	out := new(GdpPipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GdpPipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GdpPipelineInitParameters) DeepCopyInto(out *GdpPipelineInitParameters) {
	*out = *in
	if in.ApprovalKeyVaultID != nil {
		in, out := &in.ApprovalKeyVaultID, &out.ApprovalKeyVaultID
		*out = new(string)
		**out = **in
	}
	if in.ApprovalKeyVaultIDRef != nil {
		in, out := &in.ApprovalKeyVaultIDRef, &out.ApprovalKeyVaultIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ApprovalKeyVaultIDSelector != nil {
		in, out := &in.ApprovalKeyVaultIDSelector, &out.ApprovalKeyVaultIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizationDetails != nil {
		in, out := &in.AuthorizationDetails, &out.AuthorizationDetails
		*out = new(string)
		**out = **in
	}
	if in.BucketDetails != nil {
		in, out := &in.BucketDetails, &out.BucketDetails
		*out = make([]BucketDetailsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.CompartmentIDRef != nil {
		in, out := &in.CompartmentIDRef, &out.CompartmentIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.CompartmentIDSelector != nil {
		in, out := &in.CompartmentIDSelector, &out.CompartmentIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = new(string)
		**out = **in
	}
	if in.FileTypes != nil {
		in, out := &in.FileTypes, &out.FileTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IsApprovalNeeded != nil {
		in, out := &in.IsApprovalNeeded, &out.IsApprovalNeeded
		*out = new(bool)
		**out = **in
	}
	if in.IsChunkingEnabled != nil {
		in, out := &in.IsChunkingEnabled, &out.IsChunkingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsFileOverrideInDestinationEnabled != nil {
		in, out := &in.IsFileOverrideInDestinationEnabled, &out.IsFileOverrideInDestinationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsScanningEnabled != nil {
		in, out := &in.IsScanningEnabled, &out.IsScanningEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PeeringRegion != nil {
		in, out := &in.PeeringRegion, &out.PeeringRegion
		*out = new(string)
		**out = **in
	}
	if in.PipelineType != nil {
		in, out := &in.PipelineType, &out.PipelineType
		*out = new(string)
		**out = **in
	}
	if in.ServiceLogGroupID != nil {
		in, out := &in.ServiceLogGroupID, &out.ServiceLogGroupID
		*out = new(string)
		**out = **in
	}
	if in.ServiceLogGroupIDRef != nil {
		in, out := &in.ServiceLogGroupIDRef, &out.ServiceLogGroupIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceLogGroupIDSelector != nil {
		in, out := &in.ServiceLogGroupIDSelector, &out.ServiceLogGroupIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GdpPipelineInitParameters.
func (in *GdpPipelineInitParameters) DeepCopy() *GdpPipelineInitParameters {
	if in == nil {
		return nil
	}
	out := new(GdpPipelineInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GdpPipelineList) DeepCopyInto(out *GdpPipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GdpPipeline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GdpPipelineList.
func (in *GdpPipelineList) DeepCopy() *GdpPipelineList {
	if in == nil {
		return nil
	}
	out := new(GdpPipelineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GdpPipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GdpPipelineObservation) DeepCopyInto(out *GdpPipelineObservation) {
	*out = *in
	if in.ApprovalKeyVaultID != nil {
		in, out := &in.ApprovalKeyVaultID, &out.ApprovalKeyVaultID
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationDetails != nil {
		in, out := &in.AuthorizationDetails, &out.AuthorizationDetails
		*out = new(string)
		**out = **in
	}
	if in.BucketDetails != nil {
		in, out := &in.BucketDetails, &out.BucketDetails
		*out = make([]BucketDetailsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = new(string)
		**out = **in
	}
	if in.FileTypes != nil {
		in, out := &in.FileTypes, &out.FileTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsApprovalNeeded != nil {
		in, out := &in.IsApprovalNeeded, &out.IsApprovalNeeded
		*out = new(bool)
		**out = **in
	}
	if in.IsChunkingEnabled != nil {
		in, out := &in.IsChunkingEnabled, &out.IsChunkingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsFileOverrideInDestinationEnabled != nil {
		in, out := &in.IsFileOverrideInDestinationEnabled, &out.IsFileOverrideInDestinationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsScanningEnabled != nil {
		in, out := &in.IsScanningEnabled, &out.IsScanningEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LifecycleDetails != nil {
		in, out := &in.LifecycleDetails, &out.LifecycleDetails
		*out = new(string)
		**out = **in
	}
	if in.PeeredGdpPipelineID != nil {
		in, out := &in.PeeredGdpPipelineID, &out.PeeredGdpPipelineID
		*out = new(string)
		**out = **in
	}
	if in.PeeringRegion != nil {
		in, out := &in.PeeringRegion, &out.PeeringRegion
		*out = new(string)
		**out = **in
	}
	if in.PipelineType != nil {
		in, out := &in.PipelineType, &out.PipelineType
		*out = new(string)
		**out = **in
	}
	if in.ServiceLogGroupID != nil {
		in, out := &in.ServiceLogGroupID, &out.ServiceLogGroupID
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.TimeUpdated != nil {
		in, out := &in.TimeUpdated, &out.TimeUpdated
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GdpPipelineObservation.
func (in *GdpPipelineObservation) DeepCopy() *GdpPipelineObservation {
	if in == nil {
		return nil
	}
	out := new(GdpPipelineObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GdpPipelineParameters) DeepCopyInto(out *GdpPipelineParameters) {
	*out = *in
	if in.ApprovalKeyVaultID != nil {
		in, out := &in.ApprovalKeyVaultID, &out.ApprovalKeyVaultID
		*out = new(string)
		**out = **in
	}
	if in.ApprovalKeyVaultIDRef != nil {
		in, out := &in.ApprovalKeyVaultIDRef, &out.ApprovalKeyVaultIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ApprovalKeyVaultIDSelector != nil {
		in, out := &in.ApprovalKeyVaultIDSelector, &out.ApprovalKeyVaultIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizationDetails != nil {
		in, out := &in.AuthorizationDetails, &out.AuthorizationDetails
		*out = new(string)
		**out = **in
	}
	if in.BucketDetails != nil {
		in, out := &in.BucketDetails, &out.BucketDetails
		*out = make([]BucketDetailsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.CompartmentIDRef != nil {
		in, out := &in.CompartmentIDRef, &out.CompartmentIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.CompartmentIDSelector != nil {
		in, out := &in.CompartmentIDSelector, &out.CompartmentIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = new(string)
		**out = **in
	}
	if in.FileTypes != nil {
		in, out := &in.FileTypes, &out.FileTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IsApprovalNeeded != nil {
		in, out := &in.IsApprovalNeeded, &out.IsApprovalNeeded
		*out = new(bool)
		**out = **in
	}
	if in.IsChunkingEnabled != nil {
		in, out := &in.IsChunkingEnabled, &out.IsChunkingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsFileOverrideInDestinationEnabled != nil {
		in, out := &in.IsFileOverrideInDestinationEnabled, &out.IsFileOverrideInDestinationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsScanningEnabled != nil {
		in, out := &in.IsScanningEnabled, &out.IsScanningEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PeeringRegion != nil {
		in, out := &in.PeeringRegion, &out.PeeringRegion
		*out = new(string)
		**out = **in
	}
	if in.PipelineType != nil {
		in, out := &in.PipelineType, &out.PipelineType
		*out = new(string)
		**out = **in
	}
	if in.ServiceLogGroupID != nil {
		in, out := &in.ServiceLogGroupID, &out.ServiceLogGroupID
		*out = new(string)
		**out = **in
	}
	if in.ServiceLogGroupIDRef != nil {
		in, out := &in.ServiceLogGroupIDRef, &out.ServiceLogGroupIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceLogGroupIDSelector != nil {
		in, out := &in.ServiceLogGroupIDSelector, &out.ServiceLogGroupIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GdpPipelineParameters.
func (in *GdpPipelineParameters) DeepCopy() *GdpPipelineParameters {
	if in == nil {
		return nil
	}
	out := new(GdpPipelineParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GdpPipelineSpec) DeepCopyInto(out *GdpPipelineSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GdpPipelineSpec.
func (in *GdpPipelineSpec) DeepCopy() *GdpPipelineSpec {
	if in == nil {
		return nil
	}
	out := new(GdpPipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GdpPipelineStatus) DeepCopyInto(out *GdpPipelineStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GdpPipelineStatus.
func (in *GdpPipelineStatus) DeepCopy() *GdpPipelineStatus {
	if in == nil {
		return nil
	}
	out := new(GdpPipelineStatus)
	in.DeepCopyInto(out)
	return out
}
