/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DynamicSetUpdatePackagesManagementInitParameters struct {

	// The OCID of the dynamic set. This filter returns resources associated with this dynamic set.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/osmanagementhub/v1alpha1.DynamicSet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	DynamicSetID *string `json:"dynamicSetId,omitempty" tf:"dynamic_set_id,omitempty"`

	// Reference to a DynamicSet in osmanagementhub to populate dynamicSetId.
	// +kubebuilder:validation:Optional
	DynamicSetIDRef *v1.Reference `json:"dynamicSetIdRef,omitempty" tf:"-"`

	// Selector for a DynamicSet in osmanagementhub to populate dynamicSetId.
	// +kubebuilder:validation:Optional
	DynamicSetIDSelector *v1.Selector `json:"dynamicSetIdSelector,omitempty" tf:"-"`

	// The list of managed instance OCIDs to be attached/detached.
	ManagedInstances []*string `json:"managedInstances,omitempty" tf:"managed_instances,omitempty"`

	// The types of updates to be applied.
	UpdateTypes []*string `json:"updateTypes,omitempty" tf:"update_types,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []DynamicSetUpdatePackagesManagementWorkRequestDetailsInitParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type DynamicSetUpdatePackagesManagementObservation struct {

	// The OCID of the dynamic set. This filter returns resources associated with this dynamic set.
	DynamicSetID *string `json:"dynamicSetId,omitempty" tf:"dynamic_set_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The list of managed instance OCIDs to be attached/detached.
	ManagedInstances []*string `json:"managedInstances,omitempty" tf:"managed_instances,omitempty"`

	// The types of updates to be applied.
	UpdateTypes []*string `json:"updateTypes,omitempty" tf:"update_types,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []DynamicSetUpdatePackagesManagementWorkRequestDetailsObservation `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type DynamicSetUpdatePackagesManagementParameters struct {

	// The OCID of the dynamic set. This filter returns resources associated with this dynamic set.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/osmanagementhub/v1alpha1.DynamicSet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DynamicSetID *string `json:"dynamicSetId,omitempty" tf:"dynamic_set_id,omitempty"`

	// Reference to a DynamicSet in osmanagementhub to populate dynamicSetId.
	// +kubebuilder:validation:Optional
	DynamicSetIDRef *v1.Reference `json:"dynamicSetIdRef,omitempty" tf:"-"`

	// Selector for a DynamicSet in osmanagementhub to populate dynamicSetId.
	// +kubebuilder:validation:Optional
	DynamicSetIDSelector *v1.Selector `json:"dynamicSetIdSelector,omitempty" tf:"-"`

	// The list of managed instance OCIDs to be attached/detached.
	// +kubebuilder:validation:Optional
	ManagedInstances []*string `json:"managedInstances,omitempty" tf:"managed_instances,omitempty"`

	// The types of updates to be applied.
	// +kubebuilder:validation:Optional
	UpdateTypes []*string `json:"updateTypes,omitempty" tf:"update_types,omitempty"`

	// Provides the name and description of the job.
	// +kubebuilder:validation:Optional
	WorkRequestDetails []DynamicSetUpdatePackagesManagementWorkRequestDetailsParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type DynamicSetUpdatePackagesManagementWorkRequestDetailsInitParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type DynamicSetUpdatePackagesManagementWorkRequestDetailsObservation struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type DynamicSetUpdatePackagesManagementWorkRequestDetailsParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

// DynamicSetUpdatePackagesManagementSpec defines the desired state of DynamicSetUpdatePackagesManagement
type DynamicSetUpdatePackagesManagementSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DynamicSetUpdatePackagesManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DynamicSetUpdatePackagesManagementInitParameters `json:"initProvider,omitempty"`
}

// DynamicSetUpdatePackagesManagementStatus defines the observed state of DynamicSetUpdatePackagesManagement.
type DynamicSetUpdatePackagesManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DynamicSetUpdatePackagesManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DynamicSetUpdatePackagesManagement is the Schema for the DynamicSetUpdatePackagesManagements API. Provides the Dynamic Set Update Packages Management resource in Oracle Cloud Infrastructure Os Management Hub service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type DynamicSetUpdatePackagesManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DynamicSetUpdatePackagesManagementSpec   `json:"spec"`
	Status            DynamicSetUpdatePackagesManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DynamicSetUpdatePackagesManagementList contains a list of DynamicSetUpdatePackagesManagements
type DynamicSetUpdatePackagesManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DynamicSetUpdatePackagesManagement `json:"items"`
}

// Repository type metadata.
var (
	DynamicSetUpdatePackagesManagement_Kind             = "DynamicSetUpdatePackagesManagement"
	DynamicSetUpdatePackagesManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DynamicSetUpdatePackagesManagement_Kind}.String()
	DynamicSetUpdatePackagesManagement_KindAPIVersion   = DynamicSetUpdatePackagesManagement_Kind + "." + CRDGroupVersion.String()
	DynamicSetUpdatePackagesManagement_GroupVersionKind = CRDGroupVersion.WithKind(DynamicSetUpdatePackagesManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&DynamicSetUpdatePackagesManagement{}, &DynamicSetUpdatePackagesManagementList{})
}
