/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ManagedInstanceAttachSoftwareSourcesManagementInitParameters struct {

	// The OCID of the managed instance.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/osmanagementhub/v1alpha1.ManagedInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ManagedInstanceID *string `json:"managedInstanceId,omitempty" tf:"managed_instance_id,omitempty"`

	// Reference to a ManagedInstance in osmanagementhub to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDRef *v1.Reference `json:"managedInstanceIdRef,omitempty" tf:"-"`

	// Selector for a ManagedInstance in osmanagementhub to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDSelector *v1.Selector `json:"managedInstanceIdSelector,omitempty" tf:"-"`

	// The list of software source OCIDs to be attached/detached.
	SoftwareSources []*string `json:"softwareSources,omitempty" tf:"software_sources,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []ManagedInstanceAttachSoftwareSourcesManagementWorkRequestDetailsInitParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagedInstanceAttachSoftwareSourcesManagementObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the managed instance.
	ManagedInstanceID *string `json:"managedInstanceId,omitempty" tf:"managed_instance_id,omitempty"`

	// The list of software source OCIDs to be attached/detached.
	SoftwareSources []*string `json:"softwareSources,omitempty" tf:"software_sources,omitempty"`

	// Provides the name and description of the job.
	WorkRequestDetails []ManagedInstanceAttachSoftwareSourcesManagementWorkRequestDetailsObservation `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagedInstanceAttachSoftwareSourcesManagementParameters struct {

	// The OCID of the managed instance.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/osmanagementhub/v1alpha1.ManagedInstance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ManagedInstanceID *string `json:"managedInstanceId,omitempty" tf:"managed_instance_id,omitempty"`

	// Reference to a ManagedInstance in osmanagementhub to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDRef *v1.Reference `json:"managedInstanceIdRef,omitempty" tf:"-"`

	// Selector for a ManagedInstance in osmanagementhub to populate managedInstanceId.
	// +kubebuilder:validation:Optional
	ManagedInstanceIDSelector *v1.Selector `json:"managedInstanceIdSelector,omitempty" tf:"-"`

	// The list of software source OCIDs to be attached/detached.
	// +kubebuilder:validation:Optional
	SoftwareSources []*string `json:"softwareSources,omitempty" tf:"software_sources,omitempty"`

	// Provides the name and description of the job.
	// +kubebuilder:validation:Optional
	WorkRequestDetails []ManagedInstanceAttachSoftwareSourcesManagementWorkRequestDetailsParameters `json:"workRequestDetails,omitempty" tf:"work_request_details,omitempty"`
}

type ManagedInstanceAttachSoftwareSourcesManagementWorkRequestDetailsInitParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type ManagedInstanceAttachSoftwareSourcesManagementWorkRequestDetailsObservation struct {

	// User-specified information about the job. Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

type ManagedInstanceAttachSoftwareSourcesManagementWorkRequestDetailsParameters struct {

	// User-specified information about the job. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A user-friendly name for the job. The name does not have to be unique. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`
}

// ManagedInstanceAttachSoftwareSourcesManagementSpec defines the desired state of ManagedInstanceAttachSoftwareSourcesManagement
type ManagedInstanceAttachSoftwareSourcesManagementSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ManagedInstanceAttachSoftwareSourcesManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ManagedInstanceAttachSoftwareSourcesManagementInitParameters `json:"initProvider,omitempty"`
}

// ManagedInstanceAttachSoftwareSourcesManagementStatus defines the observed state of ManagedInstanceAttachSoftwareSourcesManagement.
type ManagedInstanceAttachSoftwareSourcesManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ManagedInstanceAttachSoftwareSourcesManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ManagedInstanceAttachSoftwareSourcesManagement is the Schema for the ManagedInstanceAttachSoftwareSourcesManagements API. Provides the Managed Instance Attach Software Sources Management resource in Oracle Cloud Infrastructure Os Management Hub service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type ManagedInstanceAttachSoftwareSourcesManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.softwareSources) || (has(self.initProvider) && has(self.initProvider.softwareSources))",message="spec.forProvider.softwareSources is a required parameter"
	Spec   ManagedInstanceAttachSoftwareSourcesManagementSpec   `json:"spec"`
	Status ManagedInstanceAttachSoftwareSourcesManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ManagedInstanceAttachSoftwareSourcesManagementList contains a list of ManagedInstanceAttachSoftwareSourcesManagements
type ManagedInstanceAttachSoftwareSourcesManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ManagedInstanceAttachSoftwareSourcesManagement `json:"items"`
}

// Repository type metadata.
var (
	ManagedInstanceAttachSoftwareSourcesManagement_Kind             = "ManagedInstanceAttachSoftwareSourcesManagement"
	ManagedInstanceAttachSoftwareSourcesManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ManagedInstanceAttachSoftwareSourcesManagement_Kind}.String()
	ManagedInstanceAttachSoftwareSourcesManagement_KindAPIVersion   = ManagedInstanceAttachSoftwareSourcesManagement_Kind + "." + CRDGroupVersion.String()
	ManagedInstanceAttachSoftwareSourcesManagement_GroupVersionKind = CRDGroupVersion.WithKind(ManagedInstanceAttachSoftwareSourcesManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&ManagedInstanceAttachSoftwareSourcesManagement{}, &ManagedInstanceAttachSoftwareSourcesManagementList{})
}
