/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.
// Code transformed by upjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	xpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	apisresolver "github.com/oracle/provider-oci/internal/apis"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

func (mg *DistributedAutonomousDatabase) ResolveReferences( // ResolveReferences of this DistributedAutonomousDatabase.
	ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "CloudAutonomousVmCluster", "CloudAutonomousVmClusterList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].CloudAutonomousVMClusterID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.CatalogDetails[i3].CloudAutonomousVMClusterIDRef,
				Selector:     mg.Spec.ForProvider.CatalogDetails[i3].CloudAutonomousVMClusterIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].CloudAutonomousVMClusterID")
		}
		mg.Spec.ForProvider.CatalogDetails[i3].CloudAutonomousVMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.CatalogDetails[i3].CloudAutonomousVMClusterIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Key", "KeyList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyIDRef,
				Selector:     mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyID")
		}
		mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "KeyVersion", "KeyVersionList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyVersionID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyVersionIDRef,
				Selector:     mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyVersionIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyVersionID")
		}
		mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyVersionID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyVersionIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "KeyStore", "KeyStoreList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].OkvKeyStoreID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.CatalogDetails[i3].OkvKeyStoreIDRef,
				Selector:     mg.Spec.ForProvider.CatalogDetails[i3].OkvKeyStoreIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].OkvKeyStoreID")
		}
		mg.Spec.ForProvider.CatalogDetails[i3].OkvKeyStoreID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.CatalogDetails[i3].OkvKeyStoreIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "CloudAutonomousVmCluster", "CloudAutonomousVmClusterList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterIDRef,
					Selector:     mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterID")
			}
			mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Vault", "VaultList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].VaultID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.CatalogDetails[i3].VaultIDRef,
				Selector:     mg.Spec.ForProvider.CatalogDetails[i3].VaultIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].VaultID")
		}
		mg.Spec.ForProvider.CatalogDetails[i3].VaultID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.CatalogDetails[i3].VaultIDRef = rsp.ResolvedReference

	}
	{
		m, l, err = apisresolver.GetManagedResource("identity.oci.m.upbound.io", "v1alpha1", "Compartment", "CompartmentList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.CompartmentIDRef,
			Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.DBBackupConfig); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("identity.oci.m.upbound.io", "v1alpha1", "Policy", "PolicyList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyIDRef,
					Selector:     mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyID")
			}
			mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "CloudAutonomousVmCluster", "CloudAutonomousVmClusterList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].CloudAutonomousVMClusterID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.ShardDetails[i3].CloudAutonomousVMClusterIDRef,
				Selector:     mg.Spec.ForProvider.ShardDetails[i3].CloudAutonomousVMClusterIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].CloudAutonomousVMClusterID")
		}
		mg.Spec.ForProvider.ShardDetails[i3].CloudAutonomousVMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ShardDetails[i3].CloudAutonomousVMClusterIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Key", "KeyList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].KMSKeyID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.ShardDetails[i3].KMSKeyIDRef,
				Selector:     mg.Spec.ForProvider.ShardDetails[i3].KMSKeyIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].KMSKeyID")
		}
		mg.Spec.ForProvider.ShardDetails[i3].KMSKeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ShardDetails[i3].KMSKeyIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "KeyVersion", "KeyVersionList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].KMSKeyVersionID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.ShardDetails[i3].KMSKeyVersionIDRef,
				Selector:     mg.Spec.ForProvider.ShardDetails[i3].KMSKeyVersionIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].KMSKeyVersionID")
		}
		mg.Spec.ForProvider.ShardDetails[i3].KMSKeyVersionID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ShardDetails[i3].KMSKeyVersionIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "KeyStore", "KeyStoreList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].OkvKeyStoreID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.ShardDetails[i3].OkvKeyStoreIDRef,
				Selector:     mg.Spec.ForProvider.ShardDetails[i3].OkvKeyStoreIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].OkvKeyStoreID")
		}
		mg.Spec.ForProvider.ShardDetails[i3].OkvKeyStoreID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ShardDetails[i3].OkvKeyStoreIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.ShardDetails[i3].PeerDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "CloudAutonomousVmCluster", "CloudAutonomousVmClusterList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterIDRef,
					Selector:     mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterID")
			}
			mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Vault", "VaultList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].VaultID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.ShardDetails[i3].VaultIDRef,
				Selector:     mg.Spec.ForProvider.ShardDetails[i3].VaultIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].VaultID")
		}
		mg.Spec.ForProvider.ShardDetails[i3].VaultID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ShardDetails[i3].VaultIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "CloudAutonomousVmCluster", "CloudAutonomousVmClusterList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].CloudAutonomousVMClusterID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.CatalogDetails[i3].CloudAutonomousVMClusterIDRef,
				Selector:     mg.Spec.InitProvider.CatalogDetails[i3].CloudAutonomousVMClusterIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].CloudAutonomousVMClusterID")
		}
		mg.Spec.InitProvider.CatalogDetails[i3].CloudAutonomousVMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.CatalogDetails[i3].CloudAutonomousVMClusterIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Key", "KeyList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyIDRef,
				Selector:     mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyID")
		}
		mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "KeyVersion", "KeyVersionList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyVersionID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyVersionIDRef,
				Selector:     mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyVersionIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyVersionID")
		}
		mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyVersionID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyVersionIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "KeyStore", "KeyStoreList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].OkvKeyStoreID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.CatalogDetails[i3].OkvKeyStoreIDRef,
				Selector:     mg.Spec.InitProvider.CatalogDetails[i3].OkvKeyStoreIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].OkvKeyStoreID")
		}
		mg.Spec.InitProvider.CatalogDetails[i3].OkvKeyStoreID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.CatalogDetails[i3].OkvKeyStoreIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "CloudAutonomousVmCluster", "CloudAutonomousVmClusterList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterIDRef,
					Selector:     mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterID")
			}
			mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Vault", "VaultList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].VaultID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.CatalogDetails[i3].VaultIDRef,
				Selector:     mg.Spec.InitProvider.CatalogDetails[i3].VaultIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].VaultID")
		}
		mg.Spec.InitProvider.CatalogDetails[i3].VaultID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.CatalogDetails[i3].VaultIDRef = rsp.ResolvedReference

	}
	{
		m, l, err = apisresolver.GetManagedResource("identity.oci.m.upbound.io", "v1alpha1", "Compartment", "CompartmentList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.CompartmentIDRef,
			Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.DBBackupConfig); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("identity.oci.m.upbound.io", "v1alpha1", "Policy", "PolicyList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyIDRef,
					Selector:     mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyID")
			}
			mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "CloudAutonomousVmCluster", "CloudAutonomousVmClusterList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].CloudAutonomousVMClusterID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.ShardDetails[i3].CloudAutonomousVMClusterIDRef,
				Selector:     mg.Spec.InitProvider.ShardDetails[i3].CloudAutonomousVMClusterIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].CloudAutonomousVMClusterID")
		}
		mg.Spec.InitProvider.ShardDetails[i3].CloudAutonomousVMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ShardDetails[i3].CloudAutonomousVMClusterIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Key", "KeyList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].KMSKeyID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.ShardDetails[i3].KMSKeyIDRef,
				Selector:     mg.Spec.InitProvider.ShardDetails[i3].KMSKeyIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].KMSKeyID")
		}
		mg.Spec.InitProvider.ShardDetails[i3].KMSKeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ShardDetails[i3].KMSKeyIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "KeyVersion", "KeyVersionList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].KMSKeyVersionID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.ShardDetails[i3].KMSKeyVersionIDRef,
				Selector:     mg.Spec.InitProvider.ShardDetails[i3].KMSKeyVersionIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].KMSKeyVersionID")
		}
		mg.Spec.InitProvider.ShardDetails[i3].KMSKeyVersionID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ShardDetails[i3].KMSKeyVersionIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "KeyStore", "KeyStoreList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].OkvKeyStoreID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.ShardDetails[i3].OkvKeyStoreIDRef,
				Selector:     mg.Spec.InitProvider.ShardDetails[i3].OkvKeyStoreIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].OkvKeyStoreID")
		}
		mg.Spec.InitProvider.ShardDetails[i3].OkvKeyStoreID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ShardDetails[i3].OkvKeyStoreIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.ShardDetails[i3].PeerDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "CloudAutonomousVmCluster", "CloudAutonomousVmClusterList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterIDRef,
					Selector:     mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterID")
			}
			mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].CloudAutonomousVMClusterIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Vault", "VaultList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].VaultID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.ShardDetails[i3].VaultIDRef,
				Selector:     mg.Spec.InitProvider.ShardDetails[i3].VaultIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].VaultID")
		}
		mg.Spec.InitProvider.ShardDetails[i3].VaultID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ShardDetails[i3].VaultIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this DistributedDatabase.
func (mg *DistributedDatabase) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Key", "KeyList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyIDRef,
				Selector:     mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyID")
		}
		mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "KeyVersion", "KeyVersionList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyVersionID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyVersionIDRef,
				Selector:     mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyVersionIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyVersionID")
		}
		mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyVersionID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.CatalogDetails[i3].KMSKeyVersionIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails); i4++ {
			for i5 := 0; i5 < len(mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetID),
						Extract:      resource.ExtractResourceID(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetIDRef,
						Selector:     mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetIDSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetID")
				}
				mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetIDRef = rsp.ResolvedReference

			}
		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails); i4++ {
			for i5 := 0; i5 < len(mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("dns.oci.m.upbound.io", "v1alpha1", "Zone", "ZoneList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneID),
						Extract:      resource.ExtractResourceID(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneIDRef,
						Selector:     mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneIDSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneID")
				}
				mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneIDRef = rsp.ResolvedReference

			}
		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails); i4++ {
			for i5 := 0; i5 < len(mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetID),
						Extract:      resource.ExtractResourceID(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetIDRef,
						Selector:     mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetIDSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetID")
				}
				mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetIDRef = rsp.ResolvedReference

			}
		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "VmCluster", "VmClusterList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterIDRef,
					Selector:     mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterID")
			}
			mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].BackupSubnetID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].BackupSubnetIDRef,
					Selector:     mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].BackupSubnetIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].BackupSubnetID")
			}
			mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].BackupSubnetID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].BackupSubnetIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("dns.oci.m.upbound.io", "v1alpha1", "Zone", "ZoneList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].PrivateZoneID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].PrivateZoneIDRef,
					Selector:     mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].PrivateZoneIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].PrivateZoneID")
			}
			mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].PrivateZoneID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].PrivateZoneIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].SubnetID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].SubnetIDRef,
					Selector:     mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].SubnetIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].SubnetID")
			}
			mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.CatalogDetails[i3].VMClusterDetails[i4].SubnetIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "VmCluster", "VmClusterList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].VMClusterID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.CatalogDetails[i3].VMClusterIDRef,
				Selector:     mg.Spec.ForProvider.CatalogDetails[i3].VMClusterIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].VMClusterID")
		}
		mg.Spec.ForProvider.CatalogDetails[i3].VMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.CatalogDetails[i3].VMClusterIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Vault", "VaultList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CatalogDetails[i3].VaultID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.CatalogDetails[i3].VaultIDRef,
				Selector:     mg.Spec.ForProvider.CatalogDetails[i3].VaultIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.CatalogDetails[i3].VaultID")
		}
		mg.Spec.ForProvider.CatalogDetails[i3].VaultID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.CatalogDetails[i3].VaultIDRef = rsp.ResolvedReference

	}
	{
		m, l, err = apisresolver.GetManagedResource("identity.oci.m.upbound.io", "v1alpha1", "Compartment", "CompartmentList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.CompartmentIDRef,
			Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.DBBackupConfig); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("identity.oci.m.upbound.io", "v1alpha1", "Policy", "PolicyList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyIDRef,
					Selector:     mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyID")
			}
			mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Key", "KeyList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].KMSKeyID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.ShardDetails[i3].KMSKeyIDRef,
				Selector:     mg.Spec.ForProvider.ShardDetails[i3].KMSKeyIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].KMSKeyID")
		}
		mg.Spec.ForProvider.ShardDetails[i3].KMSKeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ShardDetails[i3].KMSKeyIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "KeyVersion", "KeyVersionList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].KMSKeyVersionID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.ShardDetails[i3].KMSKeyVersionIDRef,
				Selector:     mg.Spec.ForProvider.ShardDetails[i3].KMSKeyVersionIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].KMSKeyVersionID")
		}
		mg.Spec.ForProvider.ShardDetails[i3].KMSKeyVersionID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ShardDetails[i3].KMSKeyVersionIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.ShardDetails[i3].PeerDetails); i4++ {
			for i5 := 0; i5 < len(mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetID),
						Extract:      resource.ExtractResourceID(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetIDRef,
						Selector:     mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetIDSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetID")
				}
				mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetIDRef = rsp.ResolvedReference

			}
		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.ShardDetails[i3].PeerDetails); i4++ {
			for i5 := 0; i5 < len(mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("dns.oci.m.upbound.io", "v1alpha1", "Zone", "ZoneList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneID),
						Extract:      resource.ExtractResourceID(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneIDRef,
						Selector:     mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneIDSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneID")
				}
				mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneIDRef = rsp.ResolvedReference

			}
		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.ShardDetails[i3].PeerDetails); i4++ {
			for i5 := 0; i5 < len(mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetID),
						Extract:      resource.ExtractResourceID(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetIDRef,
						Selector:     mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetIDSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetID")
				}
				mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetIDRef = rsp.ResolvedReference

			}
		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.ShardDetails[i3].PeerDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "VmCluster", "VmClusterList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterIDRef,
					Selector:     mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterID")
			}
			mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.ShardDetails[i3].PeerDetails[i4].VMClusterIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].BackupSubnetID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].BackupSubnetIDRef,
					Selector:     mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].BackupSubnetIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].BackupSubnetID")
			}
			mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].BackupSubnetID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].BackupSubnetIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("dns.oci.m.upbound.io", "v1alpha1", "Zone", "ZoneList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].PrivateZoneID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].PrivateZoneIDRef,
					Selector:     mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].PrivateZoneIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].PrivateZoneID")
			}
			mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].PrivateZoneID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].PrivateZoneIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].SubnetID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].SubnetIDRef,
					Selector:     mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].SubnetIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].SubnetID")
			}
			mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.ShardDetails[i3].VMClusterDetails[i4].SubnetIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "VmCluster", "VmClusterList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].VMClusterID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.ShardDetails[i3].VMClusterIDRef,
				Selector:     mg.Spec.ForProvider.ShardDetails[i3].VMClusterIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].VMClusterID")
		}
		mg.Spec.ForProvider.ShardDetails[i3].VMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ShardDetails[i3].VMClusterIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Vault", "VaultList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ShardDetails[i3].VaultID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.ShardDetails[i3].VaultIDRef,
				Selector:     mg.Spec.ForProvider.ShardDetails[i3].VaultIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ShardDetails[i3].VaultID")
		}
		mg.Spec.ForProvider.ShardDetails[i3].VaultID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ShardDetails[i3].VaultIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Key", "KeyList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyIDRef,
				Selector:     mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyID")
		}
		mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "KeyVersion", "KeyVersionList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyVersionID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyVersionIDRef,
				Selector:     mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyVersionIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyVersionID")
		}
		mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyVersionID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.CatalogDetails[i3].KMSKeyVersionIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails); i4++ {
			for i5 := 0; i5 < len(mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetID),
						Extract:      resource.ExtractResourceID(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetIDRef,
						Selector:     mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetIDSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetID")
				}
				mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetIDRef = rsp.ResolvedReference

			}
		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails); i4++ {
			for i5 := 0; i5 < len(mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("dns.oci.m.upbound.io", "v1alpha1", "Zone", "ZoneList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneID),
						Extract:      resource.ExtractResourceID(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneIDRef,
						Selector:     mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneIDSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneID")
				}
				mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneIDRef = rsp.ResolvedReference

			}
		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails); i4++ {
			for i5 := 0; i5 < len(mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetID),
						Extract:      resource.ExtractResourceID(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetIDRef,
						Selector:     mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetIDSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetID")
				}
				mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetIDRef = rsp.ResolvedReference

			}
		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "VmCluster", "VmClusterList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterIDRef,
					Selector:     mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterID")
			}
			mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.CatalogDetails[i3].PeerDetails[i4].VMClusterIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].BackupSubnetID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].BackupSubnetIDRef,
					Selector:     mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].BackupSubnetIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].BackupSubnetID")
			}
			mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].BackupSubnetID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].BackupSubnetIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("dns.oci.m.upbound.io", "v1alpha1", "Zone", "ZoneList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].PrivateZoneID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].PrivateZoneIDRef,
					Selector:     mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].PrivateZoneIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].PrivateZoneID")
			}
			mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].PrivateZoneID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].PrivateZoneIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].SubnetID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].SubnetIDRef,
					Selector:     mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].SubnetIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].SubnetID")
			}
			mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.CatalogDetails[i3].VMClusterDetails[i4].SubnetIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "VmCluster", "VmClusterList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].VMClusterID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.CatalogDetails[i3].VMClusterIDRef,
				Selector:     mg.Spec.InitProvider.CatalogDetails[i3].VMClusterIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].VMClusterID")
		}
		mg.Spec.InitProvider.CatalogDetails[i3].VMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.CatalogDetails[i3].VMClusterIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CatalogDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Vault", "VaultList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CatalogDetails[i3].VaultID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.CatalogDetails[i3].VaultIDRef,
				Selector:     mg.Spec.InitProvider.CatalogDetails[i3].VaultIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.CatalogDetails[i3].VaultID")
		}
		mg.Spec.InitProvider.CatalogDetails[i3].VaultID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.CatalogDetails[i3].VaultIDRef = rsp.ResolvedReference

	}
	{
		m, l, err = apisresolver.GetManagedResource("identity.oci.m.upbound.io", "v1alpha1", "Compartment", "CompartmentList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.CompartmentIDRef,
			Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.DBBackupConfig); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("identity.oci.m.upbound.io", "v1alpha1", "Policy", "PolicyList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyIDRef,
					Selector:     mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyID")
			}
			mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.DBBackupConfig[i3].BackupDestinationDetails[i4].DbrsPolicyIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Key", "KeyList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].KMSKeyID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.ShardDetails[i3].KMSKeyIDRef,
				Selector:     mg.Spec.InitProvider.ShardDetails[i3].KMSKeyIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].KMSKeyID")
		}
		mg.Spec.InitProvider.ShardDetails[i3].KMSKeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ShardDetails[i3].KMSKeyIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "KeyVersion", "KeyVersionList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].KMSKeyVersionID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.ShardDetails[i3].KMSKeyVersionIDRef,
				Selector:     mg.Spec.InitProvider.ShardDetails[i3].KMSKeyVersionIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].KMSKeyVersionID")
		}
		mg.Spec.InitProvider.ShardDetails[i3].KMSKeyVersionID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ShardDetails[i3].KMSKeyVersionIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.ShardDetails[i3].PeerDetails); i4++ {
			for i5 := 0; i5 < len(mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetID),
						Extract:      resource.ExtractResourceID(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetIDRef,
						Selector:     mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetIDSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetID")
				}
				mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].BackupSubnetIDRef = rsp.ResolvedReference

			}
		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.ShardDetails[i3].PeerDetails); i4++ {
			for i5 := 0; i5 < len(mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("dns.oci.m.upbound.io", "v1alpha1", "Zone", "ZoneList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneID),
						Extract:      resource.ExtractResourceID(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneIDRef,
						Selector:     mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneIDSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneID")
				}
				mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].PrivateZoneIDRef = rsp.ResolvedReference

			}
		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.ShardDetails[i3].PeerDetails); i4++ {
			for i5 := 0; i5 < len(mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetID),
						Extract:      resource.ExtractResourceID(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetIDRef,
						Selector:     mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetIDSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetID")
				}
				mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterDetails[i5].SubnetIDRef = rsp.ResolvedReference

			}
		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.ShardDetails[i3].PeerDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "VmCluster", "VmClusterList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterIDRef,
					Selector:     mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterID")
			}
			mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.ShardDetails[i3].PeerDetails[i4].VMClusterIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].BackupSubnetID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].BackupSubnetIDRef,
					Selector:     mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].BackupSubnetIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].BackupSubnetID")
			}
			mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].BackupSubnetID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].BackupSubnetIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("dns.oci.m.upbound.io", "v1alpha1", "Zone", "ZoneList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].PrivateZoneID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].PrivateZoneIDRef,
					Selector:     mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].PrivateZoneIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].PrivateZoneID")
			}
			mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].PrivateZoneID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].PrivateZoneIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails); i4++ {
			{
				m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].SubnetID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].SubnetIDRef,
					Selector:     mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].SubnetIDSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].SubnetID")
			}
			mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.ShardDetails[i3].VMClusterDetails[i4].SubnetIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("database.oci.m.upbound.io", "v1alpha1", "VmCluster", "VmClusterList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].VMClusterID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.ShardDetails[i3].VMClusterIDRef,
				Selector:     mg.Spec.InitProvider.ShardDetails[i3].VMClusterIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].VMClusterID")
		}
		mg.Spec.InitProvider.ShardDetails[i3].VMClusterID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ShardDetails[i3].VMClusterIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ShardDetails); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.oci.m.upbound.io", "v1alpha1", "Vault", "VaultList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ShardDetails[i3].VaultID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.ShardDetails[i3].VaultIDRef,
				Selector:     mg.Spec.InitProvider.ShardDetails[i3].VaultIDSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ShardDetails[i3].VaultID")
		}
		mg.Spec.InitProvider.ShardDetails[i3].VaultID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ShardDetails[i3].VaultIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this DistributedDatabasePrivateEndpoint.
func (mg *DistributedDatabasePrivateEndpoint) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("identity.oci.m.upbound.io", "v1alpha1", "Compartment", "CompartmentList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.CompartmentIDRef,
			Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SubnetIDRef,
			Selector:     mg.Spec.ForProvider.SubnetIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubnetID")
	}
	mg.Spec.ForProvider.SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubnetIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("identity.oci.m.upbound.io", "v1alpha1", "Compartment", "CompartmentList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.CompartmentIDRef,
			Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("networking.oci.m.upbound.io", "v1alpha1", "Subnet", "SubnetList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SubnetIDRef,
			Selector:     mg.Spec.InitProvider.SubnetIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SubnetID")
	}
	mg.Spec.InitProvider.SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubnetIDRef = rsp.ResolvedReference

	return nil
}
