/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DataFileInitParameters struct {

	// (Updatable) The APM Domain ID the request is intended for.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/apm/v1alpha1.ApmDomain
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ApmDomainID *string `json:"apmDomainId,omitempty" tf:"apm_domain_id,omitempty"`

	// Reference to a ApmDomain in apm to populate apmDomainId.
	// +kubebuilder:validation:Optional
	ApmDomainIDRef *v1.Reference `json:"apmDomainIdRef,omitempty" tf:"-"`

	// Selector for a ApmDomain in apm to populate apmDomainId.
	// +kubebuilder:validation:Optional
	ApmDomainIDSelector *v1.Selector `json:"apmDomainIdSelector,omitempty" tf:"-"`

	// (Updatable) The type of the data file.
	ApmType *string `json:"apmType,omitempty" tf:"apm_type,omitempty"`

	// The object to upload to the object store. Cannot be defined if source is defined. Either one should be defined.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// (Updatable) Optional parameter that provides presentation information for how the content should be displayed or handled by the recipient.
	ContentDisposition *string `json:"contentDisposition,omitempty" tf:"content_disposition,omitempty"`

	// (Updatable) Optional parameter indicating the content encodings applied to the request body (e.g., gzip, deflate). This value can be used by recipients to determine how to decode the content.
	ContentEncoding *string `json:"contentEncoding,omitempty" tf:"content_encoding,omitempty"`

	// (Updatable) Optional parameter that indicates the natural language of the content. This value can be used by clients or intermediaries to select or display content based on language preferences.
	ContentLanguage *string `json:"contentLanguage,omitempty" tf:"content_language,omitempty"`

	// (Updatable) Optional base64-encoded MD5 hash of the request body. If provided, the server will perform a data integrity check by computing the MD5 of the received content and comparing it to the supplied value.
	ContentMd5 *string `json:"contentMd5,omitempty" tf:"content_md5,omitempty"`

	// (Updatable) Optional parameter specifying the media type (MIME type) of the request or response body. If not specified, the default is application/octet-stream.
	ContentType *string `json:"contentType,omitempty" tf:"content_type,omitempty"`

	// The name of the data file.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/apmconfig/v1alpha1.DataFile
	DataFileName *string `json:"dataFileName,omitempty" tf:"data_file_name,omitempty"`

	// Reference to a DataFile in apmconfig to populate dataFileName.
	// +kubebuilder:validation:Optional
	DataFileNameRef *v1.Reference `json:"dataFileNameRef,omitempty" tf:"-"`

	// Selector for a DataFile in apmconfig to populate dataFileName.
	// +kubebuilder:validation:Optional
	DataFileNameSelector *v1.Selector `json:"dataFileNameSelector,omitempty" tf:"-"`

	// (Updatable) Optional user-defined metadata key and value.
	Metadata map[string]string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// An absolute path to a file on the local system. Cannot be defined if content is defined. Either one should be defined.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type DataFileObservation struct {

	// (Updatable) The APM Domain ID the request is intended for.
	ApmDomainID *string `json:"apmDomainId,omitempty" tf:"apm_domain_id,omitempty"`

	// (Updatable) The type of the data file.
	ApmType *string `json:"apmType,omitempty" tf:"apm_type,omitempty"`

	// The object to upload to the object store. Cannot be defined if source is defined. Either one should be defined.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// (Updatable) Optional parameter that provides presentation information for how the content should be displayed or handled by the recipient.
	ContentDisposition *string `json:"contentDisposition,omitempty" tf:"content_disposition,omitempty"`

	// (Updatable) Optional parameter indicating the content encodings applied to the request body (e.g., gzip, deflate). This value can be used by recipients to determine how to decode the content.
	ContentEncoding *string `json:"contentEncoding,omitempty" tf:"content_encoding,omitempty"`

	// (Updatable) Optional parameter that indicates the natural language of the content. This value can be used by clients or intermediaries to select or display content based on language preferences.
	ContentLanguage *string `json:"contentLanguage,omitempty" tf:"content_language,omitempty"`

	ContentLength *int64 `json:"contentLength,omitempty" tf:"content_length,omitempty"`

	// (Updatable) Optional base64-encoded MD5 hash of the request body. If provided, the server will perform a data integrity check by computing the MD5 of the received content and comparing it to the supplied value.
	ContentMd5 *string `json:"contentMd5,omitempty" tf:"content_md5,omitempty"`

	// (Updatable) Optional parameter specifying the media type (MIME type) of the request or response body. If not specified, the default is application/octet-stream.
	ContentType *string `json:"contentType,omitempty" tf:"content_type,omitempty"`

	// The name of the data file.
	DataFileName *string `json:"dataFileName,omitempty" tf:"data_file_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) Optional user-defined metadata key and value.
	Metadata map[string]string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// An absolute path to a file on the local system. Cannot be defined if content is defined. Either one should be defined.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	TimeLastModified *string `json:"timeLastModified,omitempty" tf:"time_last_modified,omitempty"`
}

type DataFileParameters struct {

	// (Updatable) The APM Domain ID the request is intended for.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/apm/v1alpha1.ApmDomain
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ApmDomainID *string `json:"apmDomainId,omitempty" tf:"apm_domain_id,omitempty"`

	// Reference to a ApmDomain in apm to populate apmDomainId.
	// +kubebuilder:validation:Optional
	ApmDomainIDRef *v1.Reference `json:"apmDomainIdRef,omitempty" tf:"-"`

	// Selector for a ApmDomain in apm to populate apmDomainId.
	// +kubebuilder:validation:Optional
	ApmDomainIDSelector *v1.Selector `json:"apmDomainIdSelector,omitempty" tf:"-"`

	// (Updatable) The type of the data file.
	// +kubebuilder:validation:Optional
	ApmType *string `json:"apmType,omitempty" tf:"apm_type,omitempty"`

	// The object to upload to the object store. Cannot be defined if source is defined. Either one should be defined.
	// +kubebuilder:validation:Optional
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// (Updatable) Optional parameter that provides presentation information for how the content should be displayed or handled by the recipient.
	// +kubebuilder:validation:Optional
	ContentDisposition *string `json:"contentDisposition,omitempty" tf:"content_disposition,omitempty"`

	// (Updatable) Optional parameter indicating the content encodings applied to the request body (e.g., gzip, deflate). This value can be used by recipients to determine how to decode the content.
	// +kubebuilder:validation:Optional
	ContentEncoding *string `json:"contentEncoding,omitempty" tf:"content_encoding,omitempty"`

	// (Updatable) Optional parameter that indicates the natural language of the content. This value can be used by clients or intermediaries to select or display content based on language preferences.
	// +kubebuilder:validation:Optional
	ContentLanguage *string `json:"contentLanguage,omitempty" tf:"content_language,omitempty"`

	// (Updatable) Optional base64-encoded MD5 hash of the request body. If provided, the server will perform a data integrity check by computing the MD5 of the received content and comparing it to the supplied value.
	// +kubebuilder:validation:Optional
	ContentMd5 *string `json:"contentMd5,omitempty" tf:"content_md5,omitempty"`

	// (Updatable) Optional parameter specifying the media type (MIME type) of the request or response body. If not specified, the default is application/octet-stream.
	// +kubebuilder:validation:Optional
	ContentType *string `json:"contentType,omitempty" tf:"content_type,omitempty"`

	// The name of the data file.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/apmconfig/v1alpha1.DataFile
	// +kubebuilder:validation:Optional
	DataFileName *string `json:"dataFileName,omitempty" tf:"data_file_name,omitempty"`

	// Reference to a DataFile in apmconfig to populate dataFileName.
	// +kubebuilder:validation:Optional
	DataFileNameRef *v1.Reference `json:"dataFileNameRef,omitempty" tf:"-"`

	// Selector for a DataFile in apmconfig to populate dataFileName.
	// +kubebuilder:validation:Optional
	DataFileNameSelector *v1.Selector `json:"dataFileNameSelector,omitempty" tf:"-"`

	// (Updatable) Optional user-defined metadata key and value.
	// +kubebuilder:validation:Optional
	Metadata map[string]string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// An absolute path to a file on the local system. Cannot be defined if content is defined. Either one should be defined.
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

// DataFileSpec defines the desired state of DataFile
type DataFileSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DataFileParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DataFileInitParameters `json:"initProvider,omitempty"`
}

// DataFileStatus defines the observed state of DataFile.
type DataFileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DataFileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DataFile is the Schema for the DataFiles API. Provides the Data File resource in Oracle Cloud Infrastructure Apm Config service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type DataFile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.apmType) || (has(self.initProvider) && has(self.initProvider.apmType))",message="spec.forProvider.apmType is a required parameter"
	Spec   DataFileSpec   `json:"spec"`
	Status DataFileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DataFileList contains a list of DataFiles
type DataFileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DataFile `json:"items"`
}

// Repository type metadata.
var (
	DataFile_Kind             = "DataFile"
	DataFile_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DataFile_Kind}.String()
	DataFile_KindAPIVersion   = DataFile_Kind + "." + CRDGroupVersion.String()
	DataFile_GroupVersionKind = CRDGroupVersion.WithKind(DataFile_Kind)
)

func init() {
	SchemeBuilder.Register(&DataFile{}, &DataFileList{})
}
