/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type RefreshScheduleInitParameters struct {

	// (Updatable) Specifies the type of refresh schedule.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) Specifies the refresh interval value. The interval must be provided using the ISO 8601 extended format, either as PnW or PnYnMnDTnHnMnS,  where 'P' is always required, 'T' precedes any time components less than one day, and each included component is properly suffixed.  For example, "P1DT6H" represents a duration of 1 day and 6 hours.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RefreshScheduleObservation struct {

	// (Updatable) Specifies the type of refresh schedule.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) Specifies the refresh interval value. The interval must be provided using the ISO 8601 extended format, either as PnW or PnYnMnDTnHnMnS,  where 'P' is always required, 'T' precedes any time components less than one day, and each included component is properly suffixed.  For example, "P1DT6H" represents a duration of 1 day and 6 hours.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RefreshScheduleParameters struct {

	// (Updatable) Specifies the type of refresh schedule.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// (Updatable) Specifies the refresh interval value. The interval must be provided using the ISO 8601 extended format, either as PnW or PnYnMnDTnHnMnS,  where 'P' is always required, 'T' precedes any time components less than one day, and each included component is properly suffixed.  For example, "P1DT6H" represents a duration of 1 day and 6 hours.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type SchemasInitParameters struct {

	// Specifies the type of underlying connection.
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// (Updatable) Array of database schemas or other database objects to include in enrichment pipeline.
	Schemas []SchemasSchemasInitParameters `json:"schemas,omitempty" tf:"schemas,omitempty"`
}

type SchemasObservation struct {

	// Specifies the type of underlying connection.
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// (Updatable) Array of database schemas or other database objects to include in enrichment pipeline.
	Schemas []SchemasSchemasObservation `json:"schemas,omitempty" tf:"schemas,omitempty"`
}

type SchemasParameters struct {

	// Specifies the type of underlying connection.
	// +kubebuilder:validation:Optional
	ConnectionType *string `json:"connectionType" tf:"connection_type,omitempty"`

	// (Updatable) Array of database schemas or other database objects to include in enrichment pipeline.
	// +kubebuilder:validation:Optional
	Schemas []SchemasSchemasParameters `json:"schemas" tf:"schemas,omitempty"`
}

type SchemasSchemasInitParameters struct {

	// (Updatable)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SchemasSchemasObservation struct {

	// (Updatable)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SchemasSchemasParameters struct {

	// (Updatable)
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type SemanticStoreDataSourceInitParameters struct {

	// Specifies the type of underlying connection.
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// The OCID of the Oracle Cloud Infrastructure Database Tools Connection for enrichment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.ToolsDatabaseToolsConnection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	EnrichmentConnectionID *string `json:"enrichmentConnectionId,omitempty" tf:"enrichment_connection_id,omitempty"`

	// Reference to a ToolsDatabaseToolsConnection in database to populate enrichmentConnectionId.
	// +kubebuilder:validation:Optional
	EnrichmentConnectionIDRef *v1.NamespacedReference `json:"enrichmentConnectionIdRef,omitempty" tf:"-"`

	// Selector for a ToolsDatabaseToolsConnection in database to populate enrichmentConnectionId.
	// +kubebuilder:validation:Optional
	EnrichmentConnectionIDSelector *v1.NamespacedSelector `json:"enrichmentConnectionIdSelector,omitempty" tf:"-"`

	// The OCID of the Oracle Cloud Infrastructure Database Tools Connection for querying.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.ToolsDatabaseToolsConnection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	QueryingConnectionID *string `json:"queryingConnectionId,omitempty" tf:"querying_connection_id,omitempty"`

	// Reference to a ToolsDatabaseToolsConnection in database to populate queryingConnectionId.
	// +kubebuilder:validation:Optional
	QueryingConnectionIDRef *v1.NamespacedReference `json:"queryingConnectionIdRef,omitempty" tf:"-"`

	// Selector for a ToolsDatabaseToolsConnection in database to populate queryingConnectionId.
	// +kubebuilder:validation:Optional
	QueryingConnectionIDSelector *v1.NamespacedSelector `json:"queryingConnectionIdSelector,omitempty" tf:"-"`
}

type SemanticStoreDataSourceObservation struct {

	// Specifies the type of underlying connection.
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// The OCID of the Oracle Cloud Infrastructure Database Tools Connection for enrichment.
	EnrichmentConnectionID *string `json:"enrichmentConnectionId,omitempty" tf:"enrichment_connection_id,omitempty"`

	// The OCID of the Oracle Cloud Infrastructure Database Tools Connection for querying.
	QueryingConnectionID *string `json:"queryingConnectionId,omitempty" tf:"querying_connection_id,omitempty"`
}

type SemanticStoreDataSourceParameters struct {

	// Specifies the type of underlying connection.
	// +kubebuilder:validation:Optional
	ConnectionType *string `json:"connectionType" tf:"connection_type,omitempty"`

	// The OCID of the Oracle Cloud Infrastructure Database Tools Connection for enrichment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.ToolsDatabaseToolsConnection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	EnrichmentConnectionID *string `json:"enrichmentConnectionId,omitempty" tf:"enrichment_connection_id,omitempty"`

	// Reference to a ToolsDatabaseToolsConnection in database to populate enrichmentConnectionId.
	// +kubebuilder:validation:Optional
	EnrichmentConnectionIDRef *v1.NamespacedReference `json:"enrichmentConnectionIdRef,omitempty" tf:"-"`

	// Selector for a ToolsDatabaseToolsConnection in database to populate enrichmentConnectionId.
	// +kubebuilder:validation:Optional
	EnrichmentConnectionIDSelector *v1.NamespacedSelector `json:"enrichmentConnectionIdSelector,omitempty" tf:"-"`

	// The OCID of the Oracle Cloud Infrastructure Database Tools Connection for querying.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.ToolsDatabaseToolsConnection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	QueryingConnectionID *string `json:"queryingConnectionId,omitempty" tf:"querying_connection_id,omitempty"`

	// Reference to a ToolsDatabaseToolsConnection in database to populate queryingConnectionId.
	// +kubebuilder:validation:Optional
	QueryingConnectionIDRef *v1.NamespacedReference `json:"queryingConnectionIdRef,omitempty" tf:"-"`

	// Selector for a ToolsDatabaseToolsConnection in database to populate queryingConnectionId.
	// +kubebuilder:validation:Optional
	QueryingConnectionIDSelector *v1.NamespacedSelector `json:"queryingConnectionIdSelector,omitempty" tf:"-"`
}

type SemanticStoreInitParameters struct {

	// (Updatable) Owning compartment OCID for a SemanticStore.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// Defines the data source that the semantic model connects to.
	DataSource []SemanticStoreDataSourceInitParameters `json:"dataSource,omitempty" tf:"data_source,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) An optional description of the SemanticStore.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Specifies a refresh schedule. Null represents no automated synchronization schedule.
	RefreshSchedule []RefreshScheduleInitParameters `json:"refreshSchedule,omitempty" tf:"refresh_schedule,omitempty"`

	// (Updatable) Array of database schemas or other database objects to include in enrichment pipeline.
	Schemas []SchemasInitParameters `json:"schemas,omitempty" tf:"schemas,omitempty"`
}

type SemanticStoreObservation struct {

	// (Updatable) Owning compartment OCID for a SemanticStore.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Defines the data source that the semantic model connects to.
	DataSource []SemanticStoreDataSourceObservation `json:"dataSource,omitempty" tf:"data_source,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) An optional description of the SemanticStore.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// An OCID that uniquely identifies a SemanticStore.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A message describing the current state in more detail that can provide actionable information.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// (Updatable) Specifies a refresh schedule. Null represents no automated synchronization schedule.
	RefreshSchedule []RefreshScheduleObservation `json:"refreshSchedule,omitempty" tf:"refresh_schedule,omitempty"`

	// (Updatable) Array of database schemas or other database objects to include in enrichment pipeline.
	Schemas []SchemasObservation `json:"schemas,omitempty" tf:"schemas,omitempty"`

	// The lifecycle state of a SemanticStore.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace.  Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The date and time that the SemanticStore was created in the format of an RFC3339 datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The date and time that the SemanticStore was updated in the format of an RFC3339 datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type SemanticStoreParameters struct {

	// (Updatable) Owning compartment OCID for a SemanticStore.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// Defines the data source that the semantic model connects to.
	// +kubebuilder:validation:Optional
	DataSource []SemanticStoreDataSourceParameters `json:"dataSource,omitempty" tf:"data_source,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) An optional description of the SemanticStore.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Specifies a refresh schedule. Null represents no automated synchronization schedule.
	// +kubebuilder:validation:Optional
	RefreshSchedule []RefreshScheduleParameters `json:"refreshSchedule,omitempty" tf:"refresh_schedule,omitempty"`

	// (Updatable) Array of database schemas or other database objects to include in enrichment pipeline.
	// +kubebuilder:validation:Optional
	Schemas []SchemasParameters `json:"schemas,omitempty" tf:"schemas,omitempty"`
}

// SemanticStoreSpec defines the desired state of SemanticStore
type SemanticStoreSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SemanticStoreParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SemanticStoreInitParameters `json:"initProvider,omitempty"`
}

// SemanticStoreStatus defines the observed state of SemanticStore.
type SemanticStoreStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SemanticStoreObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SemanticStore is the Schema for the SemanticStores API. Provides the Semantic Store resource in Oracle Cloud Infrastructure Generative AI service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type SemanticStore struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dataSource) || (has(self.initProvider) && has(self.initProvider.dataSource))",message="spec.forProvider.dataSource is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.schemas) || (has(self.initProvider) && has(self.initProvider.schemas))",message="spec.forProvider.schemas is a required parameter"
	Spec   SemanticStoreSpec   `json:"spec"`
	Status SemanticStoreStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SemanticStoreList contains a list of SemanticStores
type SemanticStoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SemanticStore `json:"items"`
}

// Repository type metadata.
var (
	SemanticStore_Kind             = "SemanticStore"
	SemanticStore_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SemanticStore_Kind}.String()
	SemanticStore_KindAPIVersion   = SemanticStore_Kind + "." + CRDGroupVersion.String()
	SemanticStore_GroupVersionKind = CRDGroupVersion.WithKind(SemanticStore_Kind)
)

func init() {
	SchemeBuilder.Register(&SemanticStore{}, &SemanticStoreList{})
}
